In [1]:
import pandas as pd
import os

# A good example for data science pipeline
# https://courses.cs.ut.ee/MTAT.03.227/2019_fall/uploads/Main/python_tutorial

In [2]:
PATH = "/dhi_work/students/chenj4"

In [3]:
!ls "/dhi_work/students/chenj4"

Baseline_allcountry_ahei_AllVars_2019-01-16.xlsx
Baseline_allcountry_ahei_AllVars_2019-01-16.xlsx.csv
Baseline_combpaq_AllVars_2019-01-16.xlsx
Baseline_combpaq_AllVars_2019-01-16.xlsx.csv
Baseline_morevarspureadult_AllVars_2019-01-16.xlsx
Baseline_morevarspureadult_AllVars_2019-01-16.xlsx.csv
PURE_diabetes

In [4]:
!ls -al "/dhi_work/students/chenj4"

total 400
drwx------ 3 chenj4  studies   4096 Mar 20 17:27 .
drwxr-xr-x 4 nelsonw studies   4096 Mar  9 20:32 ..
-rw-r--r-- 1 chenj4  studies  16847 Mar 20 17:27 Baseline_allcountry_ahei_AllVars_2019-01-16.xlsx
-rw-r--r-- 1 chenj4  studies  11766 Mar 20 17:25 Baseline_allcountry_ahei_AllVars_2019-01-16.xlsx.csv
-rw-r--r-- 1 chenj4  studies  22816 Mar 20 17:27 Baseline_combpaq_AllVars_2019-01-16.xlsx
-rw-r--r-- 1 chenj4  studies  21485 Mar 20 17:25 Baseline_combpaq_AllVars_2019-01-16.xlsx.csv
-rw-r--r-- 1 chenj4  studies 130622 Mar 20 17:27 Baseline_morevarspureadult_AllVars_2019-01-16.xlsx
-rw-r--r-- 1 chenj4  studies 166112 Mar 20 17:25 Baseline_morevarspureadult_AllVars_2019-01-16.xlsx.csv
drwx------ 2 chenj4  studies   4096 Mar  9 20:26 PURE_diabetes

In [5]:
print("HELLO")

HELLO

In [6]:
!ls -al "/dhi_work/students/chenj4/PURE_diabetes"

total 1052208
drwx------ 2 chenj4 studies      4096 Mar  9 20:26 .
drwx------ 3 chenj4 studies      4096 Mar 20 17:27 ..
-rwx------ 1 chenj4 studies 211030727 Mar  9 20:26 Combffq_04Apr19.dta
-rwx------ 1 chenj4 studies 397679602 Mar  9 20:26 Combpaq_04Apr19.dta
-rwx------ 1 chenj4 studies     24763 Mar  9 20:26 PAQ_Derived_2018-05-31.xlsx
-rwx------ 1 chenj4 studies 223129693 Mar  9 20:26 PBline_04Apr19.dta
-rwx------ 1 chenj4 studies  20926356 Mar  9 20:26 PEvent_04Apr19.dta
-rwx------ 1 chenj4 studies 220367908 Mar  9 20:26 PFollow_04Apr19.dta
-rwx------ 1 chenj4 studies     24612 Mar  9 20:26 ahei_derived_2018-05-31.xlsx

In [7]:
PATH = "/dhi_work/students/chenj4/PURE_diabetes"

In [8]:
Combffq = pd.read_stata(os.path.join(PATH, 'Combffq_04Apr19.dta'))
Combpaq = pd.read_stata(os.path.join(PATH, 'Combpaq_04Apr19.dta'))
PBline = pd.read_stata(os.path.join(PATH, 'PBline_04Apr19.dta'))
PEvent = pd.read_stata(os.path.join(PATH, 'PEvent_04Apr19.dta'))
PFollow = pd.read_stata(os.path.join(PATH, 'PFollow_04Apr19.dta'))

In [9]:
Combffq.count()

idno           155147
dairy          151439
fruits         151438
vegets         151439
meats          151439
redmeat        151439
wtmeat         151439
fish           151439
starch         151439
sfdrink        149502
alcohol        119611
saltfood       147735
procfood       149781
transfat       151439
nuts           138540
dairy_g        155147
fruits_g       155146
vegets_g       155147
meats_g        155147
redmeat_g      155147
wtmeat_g       155147
fish_g         155147
starch_g       155147
sfdrink_g      153210
alcohol_g      123319
saltfood_g     151443
procfood_g     153489
transfat_g     155147
nuts_g         142248
fibcereal      146714
                ...
lycopene       101890
lutzea         101890
vit_e          150418
vit_k          103761
fa_sat         155147
fa_mono        155147
fa_poly        155147
cholestrl      152200
wtredr         155147
psfat          155147
pertotfat      155147
persatfat      155147
perprotein     155147
percho         155147
permufa        155147
perpufa        155147
vegs           155147
fruitsc        155147
nutsc          155147
wtredrs        155147
fibs           155147
psfats         155147
frys           155147
aheiscore      155147
epochid        155147
key_country    155147
key_incctry    155147
key_centid     155147
key_commid     155147
key_hhid       155147
Length: 170, dtype: int64

In [10]:
# Combffq["idno"].intersect(PEvent["idno"])

In [11]:
PEvent.count()

idno           163466
subjid           3795
aid            163466
newdiab        163466
newmi          163466
newstrk        163466
newhf          163466
cvd            163466
severecvd      163466
fday_mi        161820
fday_strk      161820
fday_hf        161820
fday_cvd       161313
fday_sevcvd    161818
fday_dm        161821
fup            163466
dtype: int64

In [12]:
# let's try joining!
merged_data = PEvent.merge(Combffq,how="inner", on="idno")

In [13]:
merged_data = merged_data.merge(Combpaq, how="inner", on="idno")

In [14]:
merged_data = merged_data.merge(PFollow, how="inner", on="idno")
merged_data = merged_data.merge(PBline, how="inner", on="idno")

In [15]:
merged_data.count()

idno             300493
subjid_x           4324
aid_x            300493
newdiab          300493
newmi            300493
newstrk          300493
newhf            300493
cvd              300493
severecvd        300493
fday_mi          298634
fday_strk        298633
fday_hf          298633
fday_cvd         297340
fday_sevcvd      298632
fday_dm          298634
fup              300493
dairy            298291
fruits           298289
vegets           298291
meats            298291
redmeat          298291
wtmeat           298291
fish             298291
starch           298291
sfdrink          294240
alcohol          241033
saltfood         294004
procfood         296252
transfat         298291
nuts             275009
                  ...
efamsep          297856
enewfam          262228
strwork          170037
strhome          261707
stress           263789
strfinac         255258
delosint          58016
defeltir          58016
degaiwt           58016
detrbsle          58016
detrbcon          58016
detdeat           58016
defeldow          58014
depress           58016
bregshop         235630
bwalkdif         235816
bfreepol         239943
bstrwell         239390
marital          299898
locat            300493
tobacomb         298325
diabselfmeds     300144
hyperdef1        300069
efinstrs         255258
strwork2         170037
global_stress    248975
freqdrinker2     293855
bedtime          263175
waketime         263175
nightsleep       263175
Length: 593, dtype: int64

In [16]:
merged_data.dropna().count()

idno             0
subjid_x         0
aid_x            0
newdiab          0
newmi            0
newstrk          0
newhf            0
cvd              0
severecvd        0
fday_mi          0
fday_strk        0
fday_hf          0
fday_cvd         0
fday_sevcvd      0
fday_dm          0
fup              0
dairy            0
fruits           0
vegets           0
meats            0
redmeat          0
wtmeat           0
fish             0
starch           0
sfdrink          0
alcohol          0
saltfood         0
procfood         0
transfat         0
nuts             0
                ..
efamsep          0
enewfam          0
strwork          0
strhome          0
stress           0
strfinac         0
delosint         0
defeltir         0
degaiwt          0
detrbsle         0
detrbcon         0
detdeat          0
defeldow         0
depress          0
bregshop         0
bwalkdif         0
bfreepol         0
bstrwell         0
marital          0
locat            0
tobacomb         0
diabselfmeds     0
hyperdef1        0
efinstrs         0
strwork2         0
global_stress    0
freqdrinker2     0
bedtime          0
waketime         0
nightsleep       0
Length: 593, dtype: int64

In [17]:
merged_data.head()

,idno,subjid_x,aid_x,newdiab,newmi,newstrk,newhf,cvd,severecvd,fday_mi,...,tobacomb,diabselfmeds,hyperdef1,efinstrs,strwork2,global_stress,freqdrinker2,bedtime,waketime,nightsleep
0,10010001.0,NaN,10201921.0,0.0,0.0,0.0,0.0,0.0,0.0,2078.0,...,7.0,1.0,0.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,10010001.0,NaN,10201921.0,0.0,0.0,0.0,0.0,0.0,0.0,2078.0,...,7.0,1.0,0.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
2,10010002.0,NaN,10220021.0,0.0,0.0,0.0,0.0,0.0,0.0,1937.0,...,7.0,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,10010002.0,NaN,10220021.0,0.0,0.0,0.0,0.0,0.0,0.0,1937.0,...,7.0,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
4,10010003.0,NaN,10210011.0,0.0,0.0,0.0,0.0,0.0,0.0,2699.0,...,1.0,3.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN

In [18]:
Combffq.describe()

,idno,dairy,fruits,vegets,meats,redmeat,wtmeat,fish,starch,sfdrink,...,nutsc,wtredrs,fibs,psfats,frys,aheiscore,epochid,key_centid,key_commid,key_hhid
count,1.551470e+05,151439.000000,151438.000000,151439.000000,151439.000000,151439.000000,151439.000000,151439.000000,151439.000000,149502.000000,...,155147.000000,155147.000000,155147.000000,155147.000000,155147.000000,155147.000000,155147.00000,155147.000000,155147.000000,1.551470e+05
mean,5.784417e+09,1.518995,2.606640,4.390162,3.137615,0.995289,0.806826,0.494211,6.998909,0.195372,...,3.239697,4.289085,4.113409,6.645522,7.917159,34.490049,39667.02789,39.422283,191.548164,2.194566e+08
std,9.161031e+09,1.882021,2.844350,3.400901,2.489689,1.165644,1.313002,1.134050,3.765946,0.617775,...,3.813702,3.962157,3.335867,2.540041,3.233065,8.358739,32562.47005,32.573157,235.150985,6.542335e+08
min,1.001000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,5.655246,1001.00000,1.000000,1.000000,2.005001e+06
25%,1.300207e+09,0.163934,0.786885,2.261124,1.547058,0.173940,0.159251,0.005479,4.357143,0.000000,...,0.000000,0.927719,1.402692,4.574277,7.048472,28.953150,12001.00000,12.000000,3.000000,1.455358e+07
50%,2.665715e+09,1.000000,1.812011,4.214286,2.562476,0.650313,0.464286,0.142857,6.315068,0.000000,...,1.428571,2.299049,2.932787,6.504496,10.000000,34.455418,23501.00000,23.000000,51.000000,5.700631e+07
75%,7.602833e+09,2.071429,3.438859,5.214286,4.050150,1.360656,0.937949,0.491803,9.000000,0.122120,...,5.911007,10.000000,6.612188,9.239586,10.000000,39.882417,72001.00000,72.000000,502.000000,8.600913e+07
max,6.201001e+10,50.000000,120.367681,132.000000,44.074643,20.571429,42.503214,41.717500,99.798858,12.065574,...,10.000000,10.000000,10.000000,10.000000,10.000000,70.000000,95512.00000,95.000000,999.000000,5.006010e+09

In [19]:
# for name in sorted(Combpaq.columns):
#     print (name)

In [20]:
PEvent[PEvent["newdiab"] == 1]["newdiab"].count()

6216

In [21]:
PEvent[PEvent["newdiab"] == 0]["newdiab"].count()

157250

In [22]:
PEvent[PEvent["newdiab"] == 1]["newdiab"].count()/PEvent["newdiab"].count()

0.038026256224535988

# Create the dataset for scikit-learn

In [23]:
null_series = merged_data.isna().sum().sort_values(ascending=False) # we should drop the subjid too! (unless we use it with something else)

In [24]:
# get number of columns where null series has more than 5000 null entries

too_null_cols = null_series[(null_series>5000)] # there are 83 columns where there are more than 5k null entires

In [25]:
# now, we just need to NOT pick these columns
too_null_cols

arelig           300493
copecrl          300493
copebred         300493
datepaqdd        300493
datepaqmm        300493
datepaqyyyy      300493
pons_id          300493
subjid_x         296169
apmcsr           279131
ameat            271889
afish            271874
achips           271864
acookie          271864
asoda            271861
adelieat         271848
caflhung         271845
aoeathung        271843
canoeatfat       271843
anoeatfat        271843
aalwshung        271842
caalwshung       271842
aloneat          271839
ahungry          271838
aanxseat         271838
ablueat          271838
aexercise        271837
ahdspeat         271835
anogainwt        271834
aeatanytm        271834
caeatanytm       271834
                  ...
metrecrt525       10314
methouse          10310
pchminswk         10247
vigworkmet        10247
metjob            10222
totvigmet          9958
totwalkmet         9951
metall             9943
metguide           9943
totmodmet          9943
physact            9943
redmeat2_g         9135
fishonly           9089
meatnoprocsfa      8679
whtmeatsfa         8679
redmeatsfa         8679
fishonly_s         8478
wojfruit           6709
meatsfa            6640
dairysfa           6640
freqdrinker2       6638
fibcereal          6544
saltfood           6489
animalfat          6466
animalprotein      6466
sfdrink            6253
wojfruit_s         6098
saltfood_s         5878
sfdrink_s          5642
leisactv2          5540
Length: 368, dtype: int64

In [26]:
type(too_null_cols)

pandas.core.series.Series

In [27]:
too_null_cols.index.tolist()

['arelig',
 'copecrl',
 'copebred',
 'datepaqdd',
 'datepaqmm',
 'datepaqyyyy',
 'pons_id',
 'subjid_x',
 'apmcsr',
 'ameat',
 'afish',
 'achips',
 'acookie',
 'asoda',
 'adelieat',
 'caflhung',
 'aoeathung',
 'canoeatfat',
 'anoeatfat',
 'aalwshung',
 'caalwshung',
 'aloneat',
 'ahungry',
 'aanxseat',
 'ablueat',
 'aexercise',
 'ahdspeat',
 'anogainwt',
 'aeatanytm',
 'caeatanytm',
 'canogainwt',
 'actrlwt',
 'afrutveg',
 'cafrutveg',
 'physact_who',
 'minwk1',
 'totwalkwk',
 'totvigwk',
 'totmodwk',
 'allminswk',
 'v3vigminwk',
 'v3vigmet',
 'v3vigmind',
 'v3ldl',
 'v3triglyc',
 'v3hdl',
 'v3cholest',
 'v3tbwgt',
 'defeldow',
 'depress',
 'delosint',
 'defeltir',
 'degaiwt',
 'detrbsle',
 'detrbcon',
 'detdeat',
 'v3age',
 'v3amocupg',
 'v3aalcuse',
 'v3atobuse',
 'v3modminwk',
 'v3modmet',
 'v3modmind',
 'ptbhrs',
 'ptbminsday',
 'ptbday',
 'ptbmin',
 'prsvhrs',
 'prsmhrs',
 'prsvmin',
 'prsvminsday',
 'prsvday',
 'prsmminsday',
 'prsmmin',
 'prsmday',
 'v3prating',
 'v3bone',
 'v3mage',
 'v3vfat',
 'v3mmass',
 'v3bmr',
 'v3bfat',
 'v3frveg',
 'v3sfrveg',
 'v3trabic',
 'v3trafoo',
 'phvmin',
 'phvhrs',
 'ptbweek',
 'phvminsday',
 'beta_carot',
 'phvday',
 'alpha_carot',
 'opcigar',
 'prswhrs',
 'prsvweek',
 'prsmweek',
 'v3hip',
 'v3waist',
 'phmhrs',
 'phmmin',
 'v3dbp1',
 'v3sbp1',
 'v3height',
 'opalcoh',
 'prswmin',
 'v3weight',
 'strwork2',
 'strwork',
 'pchminsday',
 'pcwminsday',
 'pcmminsday',
 'pchday',
 'pcwday',
 'pcmday',
 'prswminsday',
 'prswday',
 'ptwhrs',
 'v3vityp',
 'v3sex',
 'phvweek',
 'totvigday',
 'pchmin',
 'pchhrs',
 'pcwhrs',
 'pcwmin',
 'pcmhrs',
 'pcmmin',
 'phmminsday',
 'phmday',
 'v3walkminwk',
 'v3walkmet',
 'v3walkmind',
 'pcmweek',
 'phmpmin',
 'phmphrs',
 'pcwweek',
 'ptmhrs',
 'beta_crypt',
 'lycopene',
 'folate_dfe',
 'lutzea',
 'food_folate',
 'folic_acid',
 'vit_k',
 'ptwmin',
 'dyveg',
 'v3metall',
 'v3physact',
 'ptwminsday',
 'ptwday',
 'dyveg_g',
 'dyveg_s',
 'ptmmin',
 'phmpminsday',
 'phmpday',
 'ptssdmin',
 'fruitjuice',
 'v3sitmind',
 'fruitjuice_s',
 'pchweek',
 'fruitjuice_g',
 'prswweek',
 'vegraw',
 'vegraw_s',
 'ptssmin',
 'vegraw_g',
 'opflour',
 'crucveg_s',
 'phmweek',
 'ptmminsday',
 'ptmday',
 'crucveg',
 'crucveg_g',
 'vegcooked_s',
 'opsnack',
 'opsdrink',
 'water',
 'vegcooked',
 'otherveg',
 'glveg',
 'otherveg_s',
 'glveg_s',
 'ptwweek',
 'glveg_g',
 'otherveg_g',
 'vegcooked_g',
 'opfdoth',
 'oprice',
 'opeoil',
 'opmainfd',
 'procmeat',
 'admala',
 'procmeat_s',
 'totwalkday',
 'procmeat_g',
 'retinol',
 'bregshop',
 'redprocsfa',
 'bwalkdif',
 'ptmweek',
 'sugar_tot',
 'v3ldlu',
 'v3triglycu',
 'v3hdlu',
 'v3cholestu',
 'totmodday',
 'phmpweek',
 'bstrwell',
 'bfreepol',
 'alcohol',
 'nutnosoy',
 'nutnosoy_s',
 'alcohol_g',
 'alcohol_s',
 'nutnosoy_g',
 'aemploy',
 'v3admeddiab',
 'v3admedbp',
 'copper',
 'manganese',
 'vit_a_rae',
 'panto_acid',
 'v3adhfail',
 'sweets',
 'global_stress',
 'sweets_s',
 'v3adhype',
 'v3addiab',
 'v3adcopd',
 'v3adstrk',
 'v3adcancer',
 'v3admi',
 'ash',
 'physactivall',
 'efinstrs',
 'strfinac',
 'allminsday',
 'ptssdhrs',
 'apmhrate1',
 'apmhrate',
 'metsitweekend',
 'sitminswkend',
 'datepaq',
 'ptsshrs',
 'niacin',
 'strhome',
 'enewfam',
 'aeth',
 'waketime',
 'nightsleep',
 'bedtime',
 'sitminswkday',
 'metsitweekday',
 'stress',
 'prsvno',
 'prsmno',
 'prswno',
 'phmpno',
 'phmno',
 'phvno',
 'ptwno',
 'ptmno',
 'ptbno',
 'pcmno',
 'pchno',
 'pcwno',
 'iso3digitcountry',
 'communityid',
 'hhid_x',
 'adsstrk',
 'adschd',
 'adshbp',
 'fev1fvc',
 'adsdiab',
 'asppefr',
 'aspfvc',
 'aspfev',
 'admstrk',
 'admchd',
 'admhbp',
 'adfstrk',
 'admdiab',
 'modworkmet',
 'pcmminswk',
 'adfhbp',
 'adhfail',
 'adfchd',
 'adfdiab',
 'occupgrp',
 'phosphorus',
 'magnesium',
 'amhwloss',
 'astrlevl',
 'adcopd',
 'adhepa',
 'subjid_y',
 'housid',
 'commid_x',
 'subjid',
 'nuts',
 'nuts_s',
 'walktransmet',
 'ptmminswk',
 'ptwminswk',
 'biketransmet',
 'ptbminswk',
 'walkworkmet',
 'pcwminswk',
 'mettrans',
 'nuts_g',
 'fishonly_g',
 'fishsfa',
 'apmdbp',
 'apmsbp',
 'whr',
 'vit_a_iu',
 'bmi',
 'apmwaist',
 'apmhip',
 'selenium',
 'apmweight',
 'vit_b12',
 'redmeat2',
 'prswminswk',
 'walkrecmet',
 'phmpminswk',
 'modhousinmet',
 'phmminswk',
 'modhousoutmet',
 'prsmminswk',
 'modrecmet',
 'redmeat2_s',
 'vighousmet',
 'phvminswk',
 'prsvminswk',
 'vigrecmet',
 'metrecrt',
 'metrecrt525',
 'methouse',
 'pchminswk',
 'vigworkmet',
 'metjob',
 'totvigmet',
 'totwalkmet',
 'metall',
 'metguide',
 'totmodmet',
 'physact',
 'redmeat2_g',
 'fishonly',
 'meatnoprocsfa',
 'whtmeatsfa',
 'redmeatsfa',
 'fishonly_s',
 'wojfruit',
 'meatsfa',
 'dairysfa',
 'freqdrinker2',
 'fibcereal',
 'saltfood',
 'animalfat',
 'animalprotein',
 'sfdrink',
 'wojfruit_s',
 'saltfood_s',
 'sfdrink_s',
 'leisactv2']

In [28]:
non_null_merged_data = merged_data.drop(too_null_cols.index.tolist(), axis=1)

In [29]:
non_null_merged_data

,idno,aid_x,newdiab,newmi,newstrk,newhf,cvd,severecvd,fday_mi,fday_strk,...,bpmedm,educ,eloss,edeath,efamsep,marital,locat,tobacomb,diabselfmeds,hyperdef1
0,1.001000e+07,10201921.0,0.0,0.0,0.0,0.0,0.0,0.0,2078.0,2078.0,...,0.0,Trade or College/University,No,No,No,Currently married,Urban,7.0,1.0,0.0
1,1.001000e+07,10201921.0,0.0,0.0,0.0,0.0,0.0,0.0,2078.0,2078.0,...,0.0,Trade or College/University,No,No,No,Currently married,Urban,7.0,1.0,0.0
2,1.001000e+07,10220021.0,0.0,0.0,0.0,0.0,0.0,0.0,1937.0,1937.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Urban,7.0,1.0,1.0
3,1.001000e+07,10220021.0,0.0,0.0,0.0,0.0,0.0,0.0,1937.0,1937.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Urban,7.0,1.0,1.0
4,1.001000e+07,10210011.0,0.0,0.0,0.0,0.0,0.0,0.0,2699.0,2699.0,...,0.0,Trade or College/University,No,No,No,Currently married,Urban,1.0,3.0,1.0
5,1.001000e+07,10210011.0,0.0,0.0,0.0,0.0,0.0,0.0,2699.0,2699.0,...,0.0,Trade or College/University,No,No,No,Currently married,Urban,1.0,3.0,1.0
6,1.001000e+07,10200091.0,0.0,0.0,0.0,0.0,0.0,0.0,6027.0,6027.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Urban,6.0,1.0,1.0
7,1.001000e+07,10200091.0,0.0,0.0,0.0,0.0,0.0,0.0,6027.0,6027.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Urban,6.0,1.0,1.0
8,1.001000e+07,10210021.0,0.0,0.0,0.0,0.0,1.0,0.0,2706.0,2706.0,...,0.0,Secondary/High/Higher secondary,Yes,Yes,No,Currently married,Urban,3.0,1.0,1.0
9,1.001000e+07,10210021.0,0.0,0.0,0.0,0.0,1.0,0.0,2706.0,2706.0,...,0.0,Secondary/High/Higher secondary,Yes,Yes,No,Currently married,Urban,3.0,1.0,1.0
10,1.001001e+07,10220031.0,0.0,0.0,0.0,0.0,0.0,0.0,4772.0,4772.0,...,1.0,"None, Primary, or Unknown",No,No,No,Currently married,Urban,2.0,3.0,1.0
11,1.001001e+07,10220031.0,0.0,0.0,0.0,0.0,0.0,0.0,4772.0,4772.0,...,1.0,"None, Primary, or Unknown",No,No,No,Currently married,Urban,2.0,3.0,1.0
12,1.001001e+07,10200061.0,0.0,0.0,0.0,0.0,0.0,0.0,2064.0,2064.0,...,0.0,Trade or College/University,No,No,No,Currently married,Urban,7.0,1.0,0.0
13,1.001001e+07,10200061.0,0.0,0.0,0.0,0.0,0.0,0.0,2064.0,2064.0,...,0.0,Trade or College/University,No,No,No,Currently married,Urban,7.0,1.0,0.0
14,1.001001e+07,10200071.0,0.0,0.0,0.0,0.0,0.0,0.0,4831.0,4831.0,...,0.0,Trade or College/University,No,No,No,Currently married,Urban,4.0,1.0,1.0
15,1.001001e+07,10200071.0,0.0,0.0,0.0,0.0,0.0,0.0,4831.0,4831.0,...,0.0,Trade or College/University,No,No,No,Currently married,Urban,4.0,1.0,1.0
16,1.001001e+07,10200092.0,0.0,0.0,0.0,0.0,0.0,0.0,6140.0,6140.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Urban,7.0,1.0,0.0
17,1.001001e+07,10200092.0,0.0,0.0,0.0,0.0,0.0,0.0,6140.0,6140.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Urban,7.0,1.0,0.0
18,1.001001e+07,10200081.0,0.0,0.0,0.0,0.0,0.0,0.0,2114.0,2114.0,...,0.0,Trade or College/University,No,No,No,Currently married,Urban,1.0,1.0,0.0
19,1.001001e+07,10200081.0,0.0,0.0,0.0,0.0,0.0,0.0,2114.0,2114.0,...,0.0,Trade or College/University,No,No,No,Currently married,Urban,1.0,1.0,0.0
20,1.001001e+07,10200031.0,0.0,0.0,0.0,0.0,0.0,0.0,5145.0,5145.0,...,0.0,"None, Primary, or Unknown",Yes,No,No,Currently married,Urban,7.0,1.0,1.0
21,1.001001e+07,10200031.0,0.0,0.0,0.0,0.0,0.0,0.0,5145.0,5145.0,...,0.0,"None, Primary, or Unknown",Yes,No,No,Currently married,Urban,7.0,1.0,1.0
22,1.001001e+07,10200042.0,0.0,0.0,0.0,0.0,0.0,0.0,5353.0,5353.0,...,0.0,"None, Primary, or Unknown",No,Yes,No,Currently married,Urban,7.0,1.0,0.0
23,1.001001e+07,10200042.0,0.0,0.0,0.0,0.0,0.0,0.0,5353.0,5353.0,...,0.0,"None, Primary, or Unknown",No,Yes,No,Currently married,Urban,7.0,1.0,0.0
24,1.001001e+07,10200051.0,0.0,0.0,0.0,0.0,0.0,0.0,2059.0,2059.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Urban,1.0,1.0,1.0
25,1.001001e+07,10200051.0,0.0,0.0,0.0,0.0,0.0,0.0,2059.0,2059.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Urban,1.0,1.0,1.0
26,1.001001e+07,10200041.0,0.0,0.0,0.0,0.0,0.0,0.0,5353.0,5353.0,...,0.0,Secondary/High/Higher secondary,No,Yes,Yes,Currently married,Urban,2.0,1.0,0.0
27,1.001001e+07,10200041.0,0.0,0.0,0.0,0.0,0.0,0.0,5353.0,5353.0,...,0.0,Secondary/High/Higher secondary,No,Yes,Yes,Currently married,Urban,2.0,1.0,0.0
28,1.001002e+07,10200082.0,0.0,0.0,0.0,0.0,0.0,0.0,2111.0,2111.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Urban,7.0,1.0,0.0
29,1.001002e+07,10200082.0,0.0,0.0,0.0,0.0,0.0,0.0,2111.0,2111.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Urban,7.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300463,6.200302e+10,65032462.0,0.0,1.0,0.0,0.0,1.0,1.0,3693.0,4455.0,...,0.0,"None, Primary, or Unknown",No,Yes,No,Currently married,Rural,7.0,1.0,0.0
300464,6.200302e+10,65032471.0,0.0,0.0,0.0,0.0,0.0,0.0,4461.0,4461.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Rural,7.0,1.0,0.0
300465,6.200302e+10,65032471.0,0.0,0.0,0.0,0.0,0.0,0.0,4461.0,4461.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Rural,7.0,1.0,0.0
300466,6.200302e+10,65032472.0,0.0,0.0,0.0,0.0,0.0,0.0,4462.0,4462.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Rural,7.0,1.0,0.0
300467,6.200302e+10,65032472.0,0.0,0.0,0.0,0.0,0.0,0.0,4462.0,4462.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Rural,7.0,1.0,0.0
300468,6.200302e+10,65032481.0,0.0,0.0,0.0,0.0,0.0,0.0,4456.0,4456.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Rural,2.0,1.0,0.0
300469,6.200302e+10,65032481.0,0.0,0.0,0.0,0.0,0.0,0.0,4456.0,4456.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Rural,2.0,1.0,0.0
300470,6.200302e+10,65032492.0,0.0,0.0,0.0,0.0,0.0,0.0,4455.0,4455.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Rural,7.0,1.0,1.0
300471,6.200302e+10,65032492.0,0.0,0.0,0.0,0.0,0.0,0.0,4455.0,4455.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Rural,7.0,1.0,1.0
300472,6.200303e+10,65032501.0,0.0,0.0,0.0,0.0,0.0,0.0,4475.0,4475.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Rural,2.0,1.0,1.0
300473,6.200303e+10,65032501.0,0.0,0.0,0.0,0.0,0.0,0.0,4475.0,4475.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Rural,2.0,1.0,1.0
300474,6.200303e+10,65032512.0,0.0,0.0,0.0,0.0,0.0,0.0,4448.0,4448.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Rural,7.0,1.0,0.0
300475,6.200303e+10,65032512.0,0.0,0.0,0.0,0.0,0.0,0.0,4448.0,4448.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Rural,7.0,1.0,0.0
300476,6.200303e+10,65032522.0,0.0,0.0,1.0,0.0,1.0,1.0,18.0,18.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Rural,7.0,1.0,1.0
300477,6.200303e+10,65032521.0,0.0,0.0,0.0,0.0,0.0,0.0,4454.0,4454.0,...,0.0,"None, Primary, or Unknown",No,No,No,Widowed,Rural,7.0,1.0,1.0
300478,6.200303e+10,65032521.0,0.0,0.0,0.0,0.0,0.0,0.0,4454.0,4454.0,...,0.0,"None, Primary, or Unknown",No,No,No,Widowed,Rural,7.0,1.0,1.0
300479,6.200303e+10,65032531.0,0.0,0.0,0.0,0.0,0.0,0.0,4692.0,4692.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Rural,2.0,1.0,0.0
300480,6.200303e+10,65032531.0,0.0,0.0,0.0,0.0,0.0,0.0,4692.0,4692.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Rural,2.0,1.0,0.0
300481,6.200303e+10,65032532.0,0.0,0.0,0.0,0.0,0.0,0.0,4691.0,4691.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Rural,7.0,1.0,0.0
300482,6.200303e+10,65032532.0,0.0,0.0,0.0,0.0,0.0,0.0,4691.0,4691.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Rural,7.0,1.0,0.0
300483,6.200303e+10,65032542.0,0.0,0.0,0.0,0.0,0.0,0.0,4428.0,4428.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Rural,7.0,1.0,0.0
300484,6.200303e+10,65032542.0,0.0,0.0,0.0,0.0,0.0,0.0,4428.0,4428.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Rural,7.0,1.0,0.0
300485,6.200303e+10,65032551.0,0.0,0.0,0.0,0.0,0.0,0.0,4431.0,4431.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Rural,2.0,1.0,0.0
300486,6.200303e+10,65032551.0,0.0,0.0,0.0,0.0,0.0,0.0,4431.0,4431.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Rural,2.0,1.0,0.0
300487,6.200303e+10,65032562.0,0.0,0.0,0.0,0.0,0.0,0.0,4434.0,4434.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Rural,7.0,1.0,1.0
300488,6.200303e+10,65032562.0,0.0,0.0,0.0,0.0,0.0,0.0,4434.0,4434.0,...,0.0,"None, Primary, or Unknown",No,No,No,Currently married,Rural,7.0,1.0,1.0
300489,6.200303e+10,65032571.0,0.0,0.0,0.0,0.0,0.0,0.0,4424.0,4424.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Rural,7.0,1.0,0.0
300490,6.200303e+10,65032571.0,0.0,0.0,0.0,0.0,0.0,0.0,4424.0,4424.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Rural,7.0,1.0,0.0
300491,6.200303e+10,65032578.0,0.0,0.0,0.0,0.0,0.0,0.0,3507.0,3507.0,...,0.0,"None, Primary, or Unknown",No,No,No,Widowed,Rural,7.0,1.0,0.0
300492,6.200303e+10,65032578.0,0.0,0.0,0.0,0.0,0.0,0.0,3507.0,3507.0,...,0.0,"None, Primary, or Unknown",No,No,No,Widowed,Rural,7.0,1.0,0.0

In [30]:
non_null_merged_data = non_null_merged_data.dropna()

In [31]:
non_null_merged_data.count()

idno             263590
aid_x            263590
newdiab          263590
newmi            263590
newstrk          263590
newhf            263590
cvd              263590
severecvd        263590
fday_mi          263590
fday_strk        263590
fday_hf          263590
fday_cvd         263590
fday_sevcvd      263590
fday_dm          263590
fup              263590
dairy            263590
fruits           263590
vegets           263590
meats            263590
redmeat          263590
wtmeat           263590
fish             263590
starch           263590
procfood         263590
transfat         263590
dairy_g          263590
fruits_g         263590
vegets_g         263590
meats_g          263590
redmeat_g        263590
                  ...
adstrok          263590
adchd            263590
adohd            263590
adcanc           263590
atobuse          263590
aalcuse          263590
hhid_y           263590
country_y        263590
new_country_y    263590
region2_y        263590
incctry_y        263590
dcode1_y         263590
dcode2_y         263590
dcode3_y         263590
dcode17_y        263590
dcode19_y        263590
epochid          263590
age              263590
alcb             263590
bline            263590
bpmedm           263590
educ             263590
eloss            263590
edeath           263590
efamsep          263590
marital          263590
locat            263590
tobacomb         263590
diabselfmeds     263590
hyperdef1        263590
Length: 225, dtype: int64

In [32]:
X_all = non_null_merged_data.drop(columns=["idno", "newdiab"])
y_all = non_null_merged_data["newdiab"] # we should be able to index back in (assuming we kept the index)

In [33]:
for col in sorted(X_all.columns):
    print(col)

aalcuse
adcanc
adchd
addiab
adohd
adstrok
adwalk
afeduc
age
aheiscore
aid_x
aid_y
alcb
amarst
amhbreath
amhcough
amhcpain
amhsfeet
applicationversion
asex
atobuse
avgsitall
bline
bpmedm
cadary
calcium
carbohydrt
centid
centid_x
centid_y
cescas_id
cholestrl
commid_y
country_x
country_y
countryname
createddate
ctry
ctryp_x
ctryp_y
cvd
dairy
dairy_g
dairy_s
dateaq
dcode10
dcode17_x
dcode17_y
dcode19_x
dcode19_y
dcode1_x
dcode1_y
dcode2_x
dcode2_y
dcode3_x
dcode3_y
dcode9
dfseq
diabselfmeds
ds_chknsk
ds_chkwsk
ds_cveget
ds_dsfdrk
ds_fatmeat
ds_frdfood
ds_fruits
ds_fryfish
ds_fveget
ds_nftmeat
ds_rice
ds_rsfdrk
ds_smilk
ds_snacks
ds_wmilk
ds_wtbread
ds_wwbread
edeath
educ
efamsep
eloss
energ_kcal
epochid
epochid_x
epochid_y
fa_mono
fa_poly
fa_sat
fday_cvd
fday_dm
fday_hf
fday_mi
fday_sevcvd
fday_strk
fiber_td
fibs
fish
fish_g
fish_s
folate_tot
fruitcat
fruits
fruits_g
fruits_s
fruitsc
frvg
frys
fup
gdpctry
gdpctryr
hhid_y
house_all
hyperdef1
incctry_x
incctry_y
incctryn
incctrynn
iron
job_all
key_centid_x
key_centid_y
key_commid_x
key_commid_y
key_country_x
key_country_y
key_hhid_x
key_hhid_y
key_incctry_x
key_incctry_y
lastmodifiedby
lastmodifieddate
legumes
legumes_g
legumes_s
leisactv1
leisactv3
leisphysact
lipid_tot
localcode
locat
location
marital
meats
meats_g
meats_s
metsit
new_centid
new_country_x
new_country_y
newhf
newmi
newstrk
nutsc
paq_internalguid
paqfi
paqln
pcjob
percho
permufa
perprotein
perpufa
persatfat
pertotfat
peru_id
phase
pintcode
poccup
potassium
procfood
procfood_g
procfood_s
protdary
protein
psfat
psfats
recrt_all
redmeat
redmeat_g
redmeat_s
region
region2_x
region2_y
region2a
regionn
ribolfavin
saltfood_g
severecvd
sfdrink_g
sodium
starch
starch_g
starch_s
studyid
subinpaq
subjectkey
sweets_g
thiamin
tobacomb
totsitall
trans_all
transfat
transfat_g
transfat_s
v3afollowd
v3afollowd0
vegetcat
vegets
vegets_g
vegets_s
vegs
version
vit_b6
vit_c
vit_e
whitemeat
whitemeat_g
whitemeat_s
wojfruit_g
wtmeat
wtmeat_g
wtmeat_s
wtredr
wtredrs
zinc

In [34]:
# some of these columns have 
len(X_all.columns)

223

In [35]:
# check the data type of the columns
# print(X_all["ctryp"])

In [36]:
for col in sorted(X_all.columns):
    print(col, X_all[col].dtype)
    
#     we could drop all the cateogires. If we have category, then we can also do a look up. That is, 
# we can try some sort of conversion from category to one hot categorical vector. But we need some sort of 
# transformer that does that! 
# ALSO, recall the data science spark datacamp tutorial! 
# that one was roughly pretty good
# Recall, we had info on how we can do various transformation methods, such as string binarization etc.

'''
The overall pipeline is as follows: 
1. We will have some EDA

df = pd.read_csv() etc.

2. We will then massage the data into the format necessary for the sklearn algo: 
3. model should be built, and then accepts the dataframe

'''

aalcuse category
adcanc category
adchd category
addiab category
adohd category
adstrok category
adwalk category
afeduc category
age float64
aheiscore float64
aid_x float64
aid_y float64
alcb category
amarst category
amhbreath float64
amhcough float64
amhcpain float64
amhsfeet float64
applicationversion object
asex category
atobuse category
avgsitall float64
bline category
bpmedm float64
cadary float64
calcium float64
carbohydrt float64
centid category
centid_x category
centid_y category
cescas_id object
cholestrl float64
commid_y float64
country_x category
country_y category
countryname object
createddate object
ctry category
ctryp_x category
ctryp_y category
cvd float64
dairy float64
dairy_g float64
dairy_s float64
dateaq datetime64[ns]
dcode10 float64
dcode17_x float64
dcode17_y category
dcode19_x float64
dcode19_y category
dcode1_x float64
dcode1_y category
dcode2_x float64
dcode2_y category
dcode3_x float64
dcode3_y category
dcode9 float64
dfseq float64
diabselfmeds float64
ds_chknsk float64
ds_chkwsk float64
ds_cveget float64
ds_dsfdrk float64
ds_fatmeat float64
ds_frdfood float64
ds_fruits float64
ds_fryfish float64
ds_fveget float64
ds_nftmeat float64
ds_rice float64
ds_rsfdrk float64
ds_smilk float64
ds_snacks float64
ds_wmilk float64
ds_wtbread float64
ds_wwbread float64
edeath category
educ category
efamsep category
eloss category
energ_kcal float64
epochid float64
epochid_x float64
epochid_y float64
fa_mono float64
fa_poly float64
fa_sat float64
fday_cvd float64
fday_dm float64
fday_hf float64
fday_mi float64
fday_sevcvd float64
fday_strk float64
fiber_td float64
fibs float64
fish float64
fish_g float64
fish_s float64
folate_tot float64
fruitcat float64
fruits float64
fruits_g float64
fruits_s float64
fruitsc float64
frvg category
frys float64
fup float64
gdpctry category
gdpctryr float64
hhid_y float64
house_all float64
hyperdef1 float64
incctry_x category
incctry_y category
incctryn float64
incctrynn float64
iron float64
job_all float64
key_centid_x float64
key_centid_y float64
key_commid_x float64
key_commid_y float64
key_country_x category
key_country_y category
key_hhid_x float64
key_hhid_y float64
key_incctry_x category
key_incctry_y category
lastmodifiedby object
lastmodifieddate object
legumes float64
legumes_g float64
legumes_s float64
leisactv1 category
leisactv3 category
leisphysact float64
lipid_tot float64
localcode object
locat category
location float64
marital category
meats float64
meats_g float64
meats_s float64
metsit float64
new_centid float64
new_country_x float64
new_country_y float64
newhf float64
newmi float64
newstrk float64
nutsc float64
paq_internalguid object
paqfi object
paqln object
pcjob float64
percho float64
permufa float64
perprotein float64
perpufa float64
persatfat float64
pertotfat float64
peru_id object
phase category
pintcode object
poccup object
potassium float64
procfood float64
procfood_g float64
procfood_s float64
protdary float64
protein float64
psfat float64
psfats float64
recrt_all float64
redmeat float64
redmeat_g float64
redmeat_s float64
region category
region2_x category
region2_y category
region2a category
regionn category
ribolfavin float64
saltfood_g float64
severecvd float64
sfdrink_g float64
sodium float64
starch float64
starch_g float64
starch_s float64
studyid object
subinpaq object
subjectkey object
sweets_g float64
thiamin float64
tobacomb float64
totsitall float64
trans_all float64
transfat float64
transfat_g float64
transfat_s float64
v3afollowd datetime64[ns]
v3afollowd0 datetime64[ns]
vegetcat float64
vegets float64
vegets_g float64
vegets_s float64
vegs float64
version object
vit_b6 float64
vit_c float64
vit_e float64
whitemeat float64
whitemeat_g float64
whitemeat_s float64
wojfruit_g float64
wtmeat float64
wtmeat_g float64
wtmeat_s float64
wtredr float64
wtredrs float64
zinc float64

'\nThe overall pipeline is as follows: \n1. We will have some EDA\n\ndf = pd.read_csv() etc.\n\n2. We will then massage the data into the format necessary for the sklearn algo: \n3. model should be built, and then accepts the dataframe\n\n'

In [37]:
X_all.head()

,aid_x,newmi,newstrk,newhf,cvd,severecvd,fday_mi,fday_strk,fday_hf,fday_cvd,...,bpmedm,educ,eloss,edeath,efamsep,marital,locat,tobacomb,diabselfmeds,hyperdef1
0,10201921.0,0.0,0.0,0.0,0.0,0.0,2078.0,2078.0,2078.0,2078.0,...,0.0,Trade or College/University,No,No,No,Currently married,Urban,7.0,1.0,0.0
1,10201921.0,0.0,0.0,0.0,0.0,0.0,2078.0,2078.0,2078.0,2078.0,...,0.0,Trade or College/University,No,No,No,Currently married,Urban,7.0,1.0,0.0
2,10220021.0,0.0,0.0,0.0,0.0,0.0,1937.0,1937.0,1937.0,1937.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Urban,7.0,1.0,1.0
3,10220021.0,0.0,0.0,0.0,0.0,0.0,1937.0,1937.0,1937.0,1937.0,...,0.0,Secondary/High/Higher secondary,No,No,No,Currently married,Urban,7.0,1.0,1.0
4,10210011.0,0.0,0.0,0.0,0.0,0.0,2699.0,2699.0,2699.0,2699.0,...,0.0,Trade or College/University,No,No,No,Currently married,Urban,1.0,3.0,1.0

In [38]:
# drop all the columns with category. 
# X_all.categorical
# to_be_dropped=pd.DataFrame(X_all.categorical).columns
X_all= X_all.select_dtypes(['number'])

In [39]:
X_all.count()

aid_x            263590
newmi            263590
newstrk          263590
newhf            263590
cvd              263590
severecvd        263590
fday_mi          263590
fday_strk        263590
fday_hf          263590
fday_cvd         263590
fday_sevcvd      263590
fday_dm          263590
fup              263590
dairy            263590
fruits           263590
vegets           263590
meats            263590
redmeat          263590
wtmeat           263590
fish             263590
starch           263590
procfood         263590
transfat         263590
dairy_g          263590
fruits_g         263590
vegets_g         263590
meats_g          263590
redmeat_g        263590
wtmeat_g         263590
fish_g           263590
                  ...
ds_wmilk         263590
ds_smilk         263590
ds_chkwsk        263590
ds_chknsk        263590
ds_fatmeat       263590
ds_nftmeat       263590
ds_fryfish       263590
ds_wwbread       263590
ds_wtbread       263590
ds_fruits        263590
ds_fveget        263590
ds_cveget        263590
ds_rsfdrk        263590
ds_dsfdrk        263590
ds_frdfood       263590
ds_snacks        263590
ds_rice          263590
commid_y         263590
amhcpain         263590
amhbreath        263590
amhcough         263590
amhsfeet         263590
hhid_y           263590
new_country_y    263590
epochid          263590
age              263590
bpmedm           263590
tobacomb         263590
diabselfmeds     263590
hyperdef1        263590
Length: 155, dtype: int64

In [40]:
# Now, we import the sci-kit learn and do everything for prediction
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2)

In [41]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# scaler.fit(X_train)
# X_train = scaler.transform(X_train)
# X_test = scaler.transform(X_test)

# # a couple things: we want to

In [42]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=2)
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=2, p=2,
           weights='uniform')

In [43]:
knn_y_pred = knn_classifier.predict(X_test)

In [44]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
print(confusion_matrix(y_test, knn_y_pred))
print(classification_report(y_test, knn_y_pred))
print(roc_auc_score(y_test, knn_y_pred))

[[50452    61]
 [  973  1232]]
             precision    recall  f1-score   support

        0.0       0.98      1.00      0.99     50513
        1.0       0.95      0.56      0.70      2205

avg / total       0.98      0.98      0.98     52718

0.778761274404

In [44]:

from sklearn.ensemble import RandomForestClassifier
rfclassifier = RandomForestClassifier()
rfclassifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [45]:

rf_y_pred = rfclassifier.predict(X_test)

In [46]:
print(confusion_matrix(y_test, rf_y_pred))
print(classification_report(y_test, rf_y_pred))
print(roc_auc_score(y_test, rf_y_pred))

[[50539     0]
 [  443  1736]]
             precision    recall  f1-score   support

        0.0       0.99      1.00      1.00     50539
        1.0       1.00      0.80      0.89      2179

avg / total       0.99      0.99      0.99     52718

0.898347865994

In [53]:

from sklearn.ensemble import AdaBoostClassifier
adaclassifier = AdaBoostClassifier()
adaclassifier.fit(X_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [55]:

ada_y_pred = adaclassifier.predict(X_test)

In [56]:
print(confusion_matrix(y_test, ada_y_pred))
print(classification_report(y_test, ada_y_pred))
print(roc_auc_score(y_test, ada_y_pred))

[[50526    13]
 [  745  1434]]
             precision    recall  f1-score   support

        0.0       0.99      1.00      0.99     50539
        1.0       0.99      0.66      0.79      2179

avg / total       0.99      0.99      0.98     52718

0.8289214094

In [ ]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
hidden_layer_sizes=(512, 256), random_state=1)

In [ ]:
clf.fit(X_train, y_train)
#Predict the response for test dataset
nn_y_pred = clf.predict(X_test)

In [ ]:
print(confusion_matrix(y_test, nn_y_pred))
print(classification_report(y_test, nn_y_pred))
print(roc_auc_score(y_test, nn_y_pred))

In [ ]:
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

In [ ]:
#Predict the response for test dataset
svm_y_pred = clf.predict(X_test)

In [ ]:
print(confusion_matrix(y_test, svm_y_pred))
print(classification_report(y_test, svm_y_pred))
print(roc_auc_score(y_test, svm_y_pred))

In [47]:
Combpaq.describe()

,iso3digitcountry,commid,housid,subjid,pcjob,pchday,pchhrs,pchmin,pchno,pcmday,...,physactivall,allminswk,totwalkwk,totmodwk,totvigwk,minwk1,physact_who,key_centid,key_commid,key_hhid
count,150239.000000,179313.000000,179313.000000,179313.000000,190586.000000,96356.000000,100624.000000,99953.000000,170800.000000,104223.000000,...,168441.000000,17426.000000,17404.000000,17404.000000,17404.000000,17404.000000,17404.000000,191691.000000,191691.000000,1.916910e+05
mean,307.134785,205.235666,218.910865,1.460747,1.487234,0.652746,0.503876,1.387982,0.851762,1.511307,...,2.218676,966.121386,182.800447,522.252722,251.913521,1118.256491,2.461618,46.139798,194.828390,1.861722e+08
std,229.158311,239.539513,234.041462,0.826748,0.499838,1.750171,1.602140,6.524731,0.355336,2.442697,...,0.774916,1014.879283,407.518006,649.509495,597.909717,1409.067814,0.818583,32.690016,235.115887,5.939961e+08
min,32.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,2.005001e+06
25%,156.000000,4.000000,41.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,2.000000,210.000000,0.000000,0.000000,0.000000,173.250000,2.000000,13.000000,4.000000,1.700420e+07
50%,156.000000,57.000000,130.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,2.000000,630.000000,0.000000,290.000000,0.000000,568.500000,3.000000,54.000000,55.000000,6.700243e+07
75%,458.000000,503.000000,323.000000,2.000000,2.000000,0.000000,0.000000,0.000000,1.000000,3.000000,...,3.000000,1407.000000,210.000000,819.000000,0.000000,1475.250000,3.000000,78.000000,502.000000,8.550425e+07
max,834.000000,999.000000,1691.000000,28.000000,2.000000,7.000000,22.000000,210.000000,1.000000,7.000000,...,3.000000,10441.000000,5040.000000,6594.000000,4620.000000,10710.000000,3.000000,95.000000,999.000000,5.006010e+09

In [48]:
PBline.describe()

,commid,subjid,amhcpain,amhbreath,amhcough,amhsfeet,amhwloss,astrlevl,caalwshung,canogainwt,...,bstrwell,tobacomb,diabselfmeds,hyperdef1,strwork2,global_stress,freqdrinker2,bedtime,waketime,nightsleep
count,198731.000000,186756.000000,187812.000000,187679.000000,187710.000000,187529.000000,161270.000000,161114.000000,10399.000000,10401.000000,...,146795.000000,197827.000000,199126.000000,199069.000000,97397.000000,145458.000000,173168.000000,152167.000000,152167.000000,152167.000000
mean,190.006889,1.476515,1.186229,1.169326,1.125779,1.115289,1.048354,2.394640,1.605827,1.983079,...,0.678415,5.390245,1.141066,0.411224,1.821227,1.947009,1.394126,66621.865713,22195.723383,8.069822
std,234.253554,0.901737,0.389292,0.375041,0.331601,0.319371,0.214513,0.764508,0.770769,0.861853,...,0.467086,2.388563,0.487490,0.492057,0.841115,0.853063,0.655467,28082.942944,5529.084859,2.536641
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,...,0.000000,4.000000,1.000000,0.000000,1.000000,1.000000,1.000000,73800.000000,19800.000000,7.000000
50%,54.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,2.000000,...,1.000000,7.000000,1.000000,0.000000,2.000000,2.000000,1.000000,79200.000000,21600.000000,8.000000
75%,502.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,2.000000,3.000000,...,1.000000,7.000000,1.000000,1.000000,2.000000,2.000000,2.000000,82800.000000,25200.000000,9.000000
max,999.000000,90.000000,2.000000,2.000000,2.000000,2.000000,2.000000,4.000000,4.000000,4.000000,...,1.000000,7.000000,3.000000,1.000000,4.000000,4.000000,3.000000,86340.000000,86340.000000,23.983333

In [49]:
PEvent.describe()

,idno,subjid,aid,newdiab,newmi,newstrk,newhf,cvd,severecvd,fday_mi,fday_strk,fday_hf,fday_cvd,fday_sevcvd,fday_dm,fup
count,1.634660e+05,3.795000e+03,1.634660e+05,163466.000000,163466.000000,163466.000000,163466.000000,163466.000000,163466.000000,161820.000000,161820.000000,161820.000000,161313.000000,161818.000000,161821.000000,163466.0
mean,5.865412e+09,2.626020e+05,3.939969e+08,0.038026,0.024501,0.023901,0.006007,0.083253,0.053754,3018.454888,3013.252015,3031.187208,2946.664113,2991.438598,2984.505009,1.0
std,9.321815e+09,3.555837e+05,3.256159e+08,0.191260,0.154597,0.152741,0.077274,0.276265,0.225533,1151.781190,1153.578675,1146.011714,1187.823443,1164.676407,1158.961276,0.0
min,1.001000e+07,1.000000e+00,1.002001e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0
25%,1.300152e+09,1.000000e+00,1.200127e+08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2426.000000,2406.000000,2471.750000,2189.000000,2324.000000,2312.000000,1.0
50%,2.665715e+09,5.000000e+00,2.350105e+08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3292.000000,3290.000000,3297.000000,3270.000000,3284.000000,3282.000000,1.0
75%,7.605201e+09,5.400680e+05,7.160199e+08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3669.000000,3665.000000,3676.000000,3644.000000,3657.000000,3654.000000,1.0
max,6.201001e+10,1.080059e+06,9.550700e+08,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6427.000000,6427.000000,6427.000000,6427.000000,6427.000000,6381.000000,1.0

In [50]:
PEvent.head()

,idno,subjid,aid,newdiab,newmi,newstrk,newhf,cvd,severecvd,fday_mi,fday_strk,fday_hf,fday_cvd,fday_sevcvd,fday_dm,fup
0,10010001.0,NaN,10201921.0,0.0,0.0,0.0,0.0,0.0,0.0,2078.0,2078.0,2078.0,2078.0,2078.0,2078.0,1.0
1,10010002.0,NaN,10220021.0,0.0,0.0,0.0,0.0,0.0,0.0,1937.0,1937.0,1937.0,1937.0,1937.0,1937.0,1.0
2,10010003.0,NaN,10210011.0,0.0,0.0,0.0,0.0,0.0,0.0,2699.0,2699.0,2699.0,2699.0,2699.0,2699.0,1.0
3,10010004.0,NaN,10200091.0,0.0,0.0,0.0,0.0,0.0,0.0,6027.0,6027.0,6027.0,6027.0,6027.0,6027.0,1.0
4,10010005.0,NaN,10210021.0,0.0,0.0,0.0,0.0,1.0,0.0,2706.0,2706.0,2706.0,2260.0,2706.0,2706.0,1.0

In [51]:
PFollow.describe()

,aid,dfseq,v3adhype,v3addiab,v3admi,v3adstrk,v3adhfail,v3adcancer,v3adcopd,v3age,...,ds_wwbread,ds_wtbread,ds_fruits,ds_fveget,ds_cveget,ds_rsfdrk,ds_dsfdrk,ds_frdfood,ds_snacks,ds_rice
count,3.400530e+05,340053.000000,280033.000000,280063.000000,280833.000000,280832.000000,276206.000000,280834.000000,280828.000000,103377.000000,...,340053.000000,340053.000000,340053.000000,340053.000000,340053.000000,340053.000000,340053.000000,340053.000000,340053.000000,340053.000000
mean,4.342930e+08,6.205292,1.308681,1.118966,1.005402,1.007499,1.000482,1.007439,1.002496,59.301121,...,0.553242,0.491815,0.676165,0.554174,0.845212,0.101507,0.050245,0.101630,0.162647,0.853625
std,3.330547e+08,2.872333,0.463948,0.330030,0.088122,0.098056,0.055960,0.097130,0.068748,10.041293,...,1.105116,1.056615,0.931984,0.816003,0.971260,0.381937,0.296384,0.254343,0.381441,1.052699
min,1.002001e+07,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.151205e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,51.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.500135e+08,6.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,59.000000,...,0.000000,0.000000,0.428571,0.142857,0.428571,0.000000,0.000000,0.000000,0.000000,0.428571
75%,7.600828e+08,9.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,67.000000,...,0.428571,0.428571,1.000000,0.785714,1.000000,0.065574,0.000000,0.065574,0.142857,1.000000
max,9.550700e+08,15.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,100.000000,...,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000

In [52]:
nutrition_vars = pd.read_table('nutritionVariables.txt', sep=',')

FileNotFoundError: File b'nutritionVariables.txt' does not exist

In [ ]:
cols = ['idno'] + list(nutrition_vars.abbreviation)
DF = Combffq[cols].merge(PEvent[['idno', 'newdiab']], left_on='idno', right_on='idno', how='inner')

In [ ]:
DF.describe()