In [1]:
import pandas as pd
import os

# A good example for data science pipeline
# https://courses.cs.ut.ee/MTAT.03.227/2019_fall/uploads/Main/python_tutorial

In [2]:
PATH = "/dhi_work/students/chenj4"

In [3]:
!ls "/dhi_work/students/chenj4"

Baseline_allcountry_ahei_AllVars_2019-01-16.xlsx
Baseline_allcountry_ahei_AllVars_2019-01-16.xlsx.csv
Baseline_combpaq_AllVars_2019-01-16.xlsx
Baseline_combpaq_AllVars_2019-01-16.xlsx.csv
Baseline_morevarspureadult_AllVars_2019-01-16.xlsx
Baseline_morevarspureadult_AllVars_2019-01-16.xlsx.csv
PURE_diabetes

In [4]:
!ls -al "/dhi_work/students/chenj4"

total 400
drwx------ 3 chenj4  studies   4096 Mar 20 17:27 .
drwxr-xr-x 4 nelsonw studies   4096 Mar  9 20:32 ..
-rw-r--r-- 1 chenj4  studies  16847 Mar 20 17:27 Baseline_allcountry_ahei_AllVars_2019-01-16.xlsx
-rw-r--r-- 1 chenj4  studies  11766 Mar 20 17:25 Baseline_allcountry_ahei_AllVars_2019-01-16.xlsx.csv
-rw-r--r-- 1 chenj4  studies  22816 Mar 20 17:27 Baseline_combpaq_AllVars_2019-01-16.xlsx
-rw-r--r-- 1 chenj4  studies  21485 Mar 20 17:25 Baseline_combpaq_AllVars_2019-01-16.xlsx.csv
-rw-r--r-- 1 chenj4  studies 130622 Mar 20 17:27 Baseline_morevarspureadult_AllVars_2019-01-16.xlsx
-rw-r--r-- 1 chenj4  studies 166112 Mar 20 17:25 Baseline_morevarspureadult_AllVars_2019-01-16.xlsx.csv
drwx------ 2 chenj4  studies   4096 Mar  9 20:26 PURE_diabetes

In [5]:
!ls -al "/dhi_work/students/chenj4/PURE_diabetes"

total 1052208
drwx------ 2 chenj4 studies      4096 Mar  9 20:26 .
drwx------ 3 chenj4 studies      4096 Mar 20 17:27 ..
-rwx------ 1 chenj4 studies 211030727 Mar  9 20:26 Combffq_04Apr19.dta
-rwx------ 1 chenj4 studies 397679602 Mar  9 20:26 Combpaq_04Apr19.dta
-rwx------ 1 chenj4 studies     24763 Mar  9 20:26 PAQ_Derived_2018-05-31.xlsx
-rwx------ 1 chenj4 studies 223129693 Mar  9 20:26 PBline_04Apr19.dta
-rwx------ 1 chenj4 studies  20926356 Mar  9 20:26 PEvent_04Apr19.dta
-rwx------ 1 chenj4 studies 220367908 Mar  9 20:26 PFollow_04Apr19.dta
-rwx------ 1 chenj4 studies     24612 Mar  9 20:26 ahei_derived_2018-05-31.xlsx

In [6]:
PATH = "/dhi_work/students/chenj4/PURE_diabetes"

In [112]:
Combffq = pd.read_stata(os.path.join(PATH, 'Combffq_04Apr19.dta'))
Combpaq = pd.read_stata(os.path.join(PATH, 'Combpaq_04Apr19.dta'))
PBline = pd.read_stata(os.path.join(PATH, 'PBline_04Apr19.dta'))
PEvent = pd.read_stata(os.path.join(PATH, 'PEvent_04Apr19.dta'))
PFollow = pd.read_stata(os.path.join(PATH, 'PFollow_04Apr19.dta'))

In [8]:
Combffq.count()

idno           155147
dairy          151439
fruits         151438
vegets         151439
meats          151439
redmeat        151439
wtmeat         151439
fish           151439
starch         151439
sfdrink        149502
alcohol        119611
saltfood       147735
procfood       149781
transfat       151439
nuts           138540
dairy_g        155147
fruits_g       155146
vegets_g       155147
meats_g        155147
redmeat_g      155147
wtmeat_g       155147
fish_g         155147
starch_g       155147
sfdrink_g      153210
alcohol_g      123319
saltfood_g     151443
procfood_g     153489
transfat_g     155147
nuts_g         142248
fibcereal      146714
                ...
lycopene       101890
lutzea         101890
vit_e          150418
vit_k          103761
fa_sat         155147
fa_mono        155147
fa_poly        155147
cholestrl      152200
wtredr         155147
psfat          155147
pertotfat      155147
persatfat      155147
perprotein     155147
percho         155147
permufa        155147
perpufa        155147
vegs           155147
fruitsc        155147
nutsc          155147
wtredrs        155147
fibs           155147
psfats         155147
frys           155147
aheiscore      155147
epochid        155147
key_country    155147
key_incctry    155147
key_centid     155147
key_commid     155147
key_hhid       155147
Length: 170, dtype: int64

In [9]:
# Combffq["idno"].intersect(PEvent["idno"])

In [10]:
PEvent.count()

idno           163466
subjid           3795
aid            163466
newdiab        163466
newmi          163466
newstrk        163466
newhf          163466
cvd            163466
severecvd      163466
fday_mi        161820
fday_strk      161820
fday_hf        161820
fday_cvd       161313
fday_sevcvd    161818
fday_dm        161821
fup            163466
dtype: int64

In [43]:
# let's try joining!
merged_data = PEvent.merge(Combffq,how="inner", on="idno")

In [114]:
merged_data = merged_data.merge(Combpaq, how="inner", on="idno")

In [115]:
merged_data.count()

idno             145742
subjid_x           3037
aid              145742
newdiab          145742
newmi            145742
newstrk          145742
newhf            145742
cvd              145742
severecvd        145742
fday_mi          144418
fday_strk        144418
fday_hf          144418
fday_cvd         143932
fday_sevcvd      144416
fday_dm          144419
fup              145742
dairy            144098
fruits           144097
vegets           144098
meats            144098
redmeat          144098
wtmeat           144098
fish             144098
starch           144098
sfdrink          142174
alcohol          115620
saltfood         140441
procfood         142487
transfat         144098
nuts             131870
                  ...
job_all          145742
trans_all        145742
house_all        145742
recrt_all        145742
sitminswkday     128548
sitminswkend     125913
metsit           145470
metsitweekday    128548
metsitweekend    125913
totsitall        145084
avgsitall        145084
metrecrt525      141180
totwalkmet       141364
totmodmet        141367
totvigmet        141359
physactivall     125077
physact          141367
metguide         141367
studyid          145742
allminswk         16307
totwalkwk         16290
totmodwk          16290
totvigwk          16290
minwk1            16290
physact_who       16290
key_country_y    145742
key_incctry_y    145742
key_centid_y     145742
key_commid_y     145742
key_hhid_y       145742
Length: 373, dtype: int64

In [116]:
merged_data.dropna().count()

idno             0
subjid_x         0
aid              0
newdiab          0
newmi            0
newstrk          0
newhf            0
cvd              0
severecvd        0
fday_mi          0
fday_strk        0
fday_hf          0
fday_cvd         0
fday_sevcvd      0
fday_dm          0
fup              0
dairy            0
fruits           0
vegets           0
meats            0
redmeat          0
wtmeat           0
fish             0
starch           0
sfdrink          0
alcohol          0
saltfood         0
procfood         0
transfat         0
nuts             0
                ..
job_all          0
trans_all        0
house_all        0
recrt_all        0
sitminswkday     0
sitminswkend     0
metsit           0
metsitweekday    0
metsitweekend    0
totsitall        0
avgsitall        0
metrecrt525      0
totwalkmet       0
totmodmet        0
totvigmet        0
physactivall     0
physact          0
metguide         0
studyid          0
allminswk        0
totwalkwk        0
totmodwk         0
totvigwk         0
minwk1           0
physact_who      0
key_country_y    0
key_incctry_y    0
key_centid_y     0
key_commid_y     0
key_hhid_y       0
Length: 373, dtype: int64

In [117]:
merged_data.head()

,idno,subjid_x,aid,newdiab,newmi,newstrk,newhf,cvd,severecvd,fday_mi,...,totwalkwk,totmodwk,totvigwk,minwk1,physact_who,key_country_y,key_incctry_y,key_centid_y,key_commid_y,key_hhid_y
0,10010001.0,NaN,10201921.0,0.0,0.0,0.0,0.0,0.0,0.0,2078.0,...,180.000000,0.0,0.0,148.500000,1.0,India,4.LIC,1.0,1.0,1.002010e+09
1,10010002.0,NaN,10220021.0,0.0,0.0,0.0,0.0,0.0,0.0,1937.0,...,1127.142857,180.0,0.0,1064.892857,3.0,India,4.LIC,1.0,1.0,1.003010e+09
2,10010003.0,NaN,10210011.0,0.0,0.0,0.0,0.0,0.0,0.0,2699.0,...,360.000000,0.0,0.0,297.000000,2.0,India,4.LIC,1.0,1.0,1.005010e+09
3,10010004.0,NaN,10200091.0,0.0,0.0,0.0,0.0,0.0,0.0,6027.0,...,360.000000,210.0,0.0,454.500000,3.0,India,4.LIC,1.0,1.0,1.001010e+09
4,10010005.0,NaN,10210021.0,0.0,0.0,0.0,0.0,1.0,0.0,2706.0,...,1440.000000,0.0,0.0,1188.000000,3.0,India,4.LIC,1.0,1.0,1.004010e+09

In [118]:
Combffq.describe()

,idno,dairy,fruits,vegets,meats,redmeat,wtmeat,fish,starch,sfdrink,...,nutsc,wtredrs,fibs,psfats,frys,aheiscore,epochid,key_centid,key_commid,key_hhid
count,1.551470e+05,151439.000000,151438.000000,151439.000000,151439.000000,151439.000000,151439.000000,151439.000000,151439.000000,149502.000000,...,155147.000000,155147.000000,155147.000000,155147.000000,155147.000000,155147.000000,155147.00000,155147.000000,155147.000000,1.551470e+05
mean,5.784417e+09,1.518995,2.606640,4.390162,3.137615,0.995289,0.806826,0.494211,6.998909,0.195372,...,3.239697,4.289085,4.113409,6.645522,7.917159,34.490049,39667.02789,39.422283,191.548164,2.194566e+08
std,9.161031e+09,1.882021,2.844350,3.400901,2.489689,1.165644,1.313002,1.134050,3.765946,0.617775,...,3.813702,3.962157,3.335867,2.540041,3.233065,8.358739,32562.47005,32.573157,235.150985,6.542335e+08
min,1.001000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,5.655246,1001.00000,1.000000,1.000000,2.005001e+06
25%,1.300207e+09,0.163934,0.786885,2.261124,1.547058,0.173940,0.159251,0.005479,4.357143,0.000000,...,0.000000,0.927719,1.402692,4.574277,7.048472,28.953150,12001.00000,12.000000,3.000000,1.455358e+07
50%,2.665715e+09,1.000000,1.812011,4.214286,2.562476,0.650313,0.464286,0.142857,6.315068,0.000000,...,1.428571,2.299049,2.932787,6.504496,10.000000,34.455418,23501.00000,23.000000,51.000000,5.700631e+07
75%,7.602833e+09,2.071429,3.438859,5.214286,4.050150,1.360656,0.937949,0.491803,9.000000,0.122120,...,5.911007,10.000000,6.612188,9.239586,10.000000,39.882417,72001.00000,72.000000,502.000000,8.600913e+07
max,6.201001e+10,50.000000,120.367681,132.000000,44.074643,20.571429,42.503214,41.717500,99.798858,12.065574,...,10.000000,10.000000,10.000000,10.000000,10.000000,70.000000,95512.00000,95.000000,999.000000,5.006010e+09

In [119]:
# for name in sorted(Combpaq.columns):
#     print (name)

In [120]:
PEvent[PEvent["newdiab"] == 1]["newdiab"].count()

6216

In [121]:
PEvent[PEvent["newdiab"] == 0]["newdiab"].count()

157250

In [122]:
PEvent[PEvent["newdiab"] == 1]["newdiab"].count()/PEvent["newdiab"].count()

0.038026256224535988

# Create the dataset for scikit-learn

In [123]:
null_series = merged_data.isna().sum().sort_values(ascending=False) # we should drop the subjid too! (unless we use it with something else)

In [124]:
# get number of columns where null series has more than 5000 null entries

too_null_cols = null_series[(null_series>5000)] # there are 83 columns where there are more than 5k null entires

In [125]:
# now, we just need to NOT pick these columns
too_null_cols

datepaqyyyy      145742
pons_id          145742
datepaqdd        145742
datepaqmm        145742
subjid_x         142705
physact_who      129452
minwk1           129452
totvigwk         129452
totmodwk         129452
totwalkwk        129452
allminswk        129435
ptbhrs            83100
ptbminsday        82679
ptbday            82615
beta_carot        82406
ptbmin            81842
prsvhrs           81507
prsmhrs           81147
prsvmin           81109
prsvminsday       81059
prsvday           81011
alpha_carot       80746
prsmminsday       80083
prsmday           80014
prsmmin           79758
phvmin            74676
phvhrs            74340
ptbweek           73190
phvminsday        73022
phvday            72939
                  ...
walktransmet      11604
ptmminswk         11570
ptbminswk         11441
biketransmet      11441
walkworkmet       11357
pcwminswk         11357
mettrans          11302
fishonly_g        11046
magnesium          9812
phosphorus         9812
redmeat2           8852
redmeat2_s         8799
vit_a_iu           8032
selenium           7940
redmeatsfa         7772
whtmeatsfa         7772
meatnoprocsfa      7772
redmeat2_g         7208
fishonly           6806
fishonly_s         6753
vit_b12            6306
dairysfa           6161
meatsfa            6161
wojfruit           5962
fibcereal          5928
wojfruit_s         5909
saltfood           5301
animalfat          5291
animalprotein      5291
saltfood_s         5248
Length: 191, dtype: int64

In [126]:
type(too_null_cols)

pandas.core.series.Series

In [127]:
too_null_cols.index.tolist()

['datepaqyyyy',
 'pons_id',
 'datepaqdd',
 'datepaqmm',
 'subjid_x',
 'physact_who',
 'minwk1',
 'totvigwk',
 'totmodwk',
 'totwalkwk',
 'allminswk',
 'ptbhrs',
 'ptbminsday',
 'ptbday',
 'beta_carot',
 'ptbmin',
 'prsvhrs',
 'prsmhrs',
 'prsvmin',
 'prsvminsday',
 'prsvday',
 'alpha_carot',
 'prsmminsday',
 'prsmday',
 'prsmmin',
 'phvmin',
 'phvhrs',
 'ptbweek',
 'phvminsday',
 'phvday',
 'prswhrs',
 'prsvweek',
 'prsmweek',
 'phmhrs',
 'pchminsday',
 'pcwminsday',
 'pcmminsday',
 'pchday',
 'pcwday',
 'prswmin',
 'pcmday',
 'dyveg',
 'phmmin',
 'prswminsday',
 'prswday',
 'fruitjuice',
 'dyveg_s',
 'dyveg_g',
 'fruitjuice_s',
 'ptwhrs',
 'totvigday',
 'fruitjuice_g',
 'pchmin',
 'pchhrs',
 'pcwhrs',
 'pcwmin',
 'pcmhrs',
 'pcmmin',
 'phvweek',
 'phmminsday',
 'phmday',
 'vegraw',
 'vegraw_s',
 'vegraw_g',
 'crucveg_s',
 'pcmweek',
 'phmpmin',
 'crucveg_g',
 'crucveg',
 'phmphrs',
 'vegcooked_s',
 'pcwweek',
 'ptmhrs',
 'glveg',
 'vegcooked',
 'otherveg',
 'otherveg_s',
 'glveg_s',
 'glveg_g',
 'otherveg_g',
 'vegcooked_g',
 'ptwmin',
 'phmpminsday',
 'ptwminsday',
 'phmpday',
 'ptwday',
 'beta_crypt',
 'lycopene',
 'folic_acid',
 'food_folate',
 'folate_dfe',
 'lutzea',
 'vit_k',
 'ptmmin',
 'pchweek',
 'prswweek',
 'ptssdmin',
 'ptmminsday',
 'ptmday',
 'ptssmin',
 'phmweek',
 'procmeat',
 'procmeat_s',
 'ptwweek',
 'water',
 'procmeat_g',
 'redprocsfa',
 'totwalkday',
 'retinol',
 'ptmweek',
 'nutnosoy',
 'alcohol',
 'nutnosoy_s',
 'sugar_tot',
 'phmpweek',
 'totmodday',
 'nutnosoy_g',
 'alcohol_g',
 'alcohol_s',
 'sweets',
 'sweets_s',
 'allminsday',
 'ptssdhrs',
 'physactivall',
 'copper',
 'vit_a_rae',
 'manganese',
 'panto_acid',
 'metsitweekend',
 'sitminswkend',
 'datepaq',
 'ptsshrs',
 'ash',
 'sitminswkday',
 'metsitweekday',
 'prsmno',
 'prsvno',
 'prswno',
 'phmpno',
 'phvno',
 'phmno',
 'ptbno',
 'ptmno',
 'ptwno',
 'pcmno',
 'pchno',
 'pcwno',
 'communityid',
 'hhid',
 'iso3digitcountry',
 'fishsfa',
 'nuts',
 'niacin',
 'nuts_s',
 'modworkmet',
 'pcmminswk',
 'housid',
 'commid',
 'subjid_y',
 'nuts_g',
 'ptwminswk',
 'walktransmet',
 'ptmminswk',
 'ptbminswk',
 'biketransmet',
 'walkworkmet',
 'pcwminswk',
 'mettrans',
 'fishonly_g',
 'magnesium',
 'phosphorus',
 'redmeat2',
 'redmeat2_s',
 'vit_a_iu',
 'selenium',
 'redmeatsfa',
 'whtmeatsfa',
 'meatnoprocsfa',
 'redmeat2_g',
 'fishonly',
 'fishonly_s',
 'vit_b12',
 'dairysfa',
 'meatsfa',
 'wojfruit',
 'fibcereal',
 'wojfruit_s',
 'saltfood',
 'animalfat',
 'animalprotein',
 'saltfood_s']

In [128]:
non_null_merged_data = merged_data.drop(too_null_cols.index.tolist(), axis=1)

In [129]:
non_null_merged_data

,idno,aid,newdiab,newmi,newstrk,newhf,cvd,severecvd,fday_mi,fday_strk,...,totmodmet,totvigmet,physact,metguide,studyid,key_country_y,key_incctry_y,key_centid_y,key_commid_y,key_hhid_y
0,1.001000e+07,10201921.0,0.0,0.0,0.0,0.0,0.0,0.0,2078.0,2078.0,...,0.0,0.0,Low PA -- Met score < 600,No,01 0001,India,4.LIC,1.0,1.0,1.002010e+09
1,1.001000e+07,10220021.0,0.0,0.0,0.0,0.0,0.0,0.0,1937.0,1937.0,...,540.0,0.0,High PA -- Met score >= 3000,Yes,01 0002,India,4.LIC,1.0,1.0,1.003010e+09
2,1.001000e+07,10210011.0,0.0,0.0,0.0,0.0,0.0,0.0,2699.0,2699.0,...,0.0,0.0,Moderate PA -- Met score in 600-3000,Yes,01 0003,India,4.LIC,1.0,1.0,1.005010e+09
3,1.001000e+07,10200091.0,0.0,0.0,0.0,0.0,0.0,0.0,6027.0,6027.0,...,630.0,0.0,Moderate PA -- Met score in 600-3000,Yes,01 0004,India,4.LIC,1.0,1.0,1.001010e+09
4,1.001000e+07,10210021.0,0.0,0.0,0.0,0.0,1.0,0.0,2706.0,2706.0,...,0.0,0.0,High PA -- Met score >= 3000,Yes,01 0005,India,4.LIC,1.0,1.0,1.004010e+09
5,1.001001e+07,10220031.0,0.0,0.0,0.0,0.0,0.0,0.0,4772.0,4772.0,...,672.0,0.0,High PA -- Met score >= 3000,Yes,01 0006,India,4.LIC,1.0,1.0,1.001010e+09
6,1.001001e+07,10200061.0,0.0,0.0,0.0,0.0,0.0,0.0,2064.0,2064.0,...,0.0,0.0,High PA -- Met score >= 3000,Yes,01 0007,India,4.LIC,1.0,1.0,1.005010e+09
7,1.001001e+07,10200071.0,0.0,0.0,0.0,0.0,0.0,0.0,4831.0,4831.0,...,0.0,0.0,Moderate PA -- Met score in 600-3000,Yes,01 0008,India,4.LIC,1.0,1.0,1.003010e+09
8,1.001001e+07,10200092.0,0.0,0.0,0.0,0.0,0.0,0.0,6140.0,6140.0,...,630.0,0.0,Moderate PA -- Met score in 600-3000,Yes,01 0009,India,4.LIC,1.0,1.0,1.001010e+09
9,1.001001e+07,10200081.0,0.0,0.0,0.0,0.0,0.0,0.0,2114.0,2114.0,...,0.0,0.0,Moderate PA -- Met score in 600-3000,Yes,01 0010,India,4.LIC,1.0,1.0,1.004010e+09
10,1.001001e+07,10200031.0,0.0,0.0,0.0,0.0,0.0,0.0,5145.0,5145.0,...,0.0,0.0,Low PA -- Met score < 600,No,01 0011,India,4.LIC,1.0,1.0,1.004010e+09
11,1.001001e+07,10200042.0,0.0,0.0,0.0,0.0,0.0,0.0,5353.0,5353.0,...,3015.0,0.0,High PA -- Met score >= 3000,Yes,01 0012,India,4.LIC,1.0,1.0,1.002010e+09
12,1.001001e+07,10200051.0,0.0,0.0,0.0,0.0,0.0,0.0,2059.0,2059.0,...,84.0,0.0,Moderate PA -- Met score in 600-3000,Yes,01 0013,India,4.LIC,1.0,1.0,1.003010e+09
13,1.001001e+07,10200041.0,0.0,0.0,0.0,0.0,0.0,0.0,5353.0,5353.0,...,0.0,0.0,Low PA -- Met score < 600,No,01 0014,India,4.LIC,1.0,1.0,1.002010e+09
14,1.001002e+07,10200082.0,0.0,0.0,0.0,0.0,0.0,0.0,2111.0,2111.0,...,2919.0,5760.0,High PA -- Met score >= 3000,Yes,01 0015,India,4.LIC,1.0,1.0,1.004010e+09
15,1.001002e+07,10200021.0,0.0,0.0,0.0,0.0,0.0,0.0,2047.0,2047.0,...,0.0,0.0,Low PA -- Met score < 600,No,01 0016,India,4.LIC,1.0,1.0,1.001010e+09
16,1.001002e+07,10220011.0,0.0,0.0,0.0,0.0,0.0,0.0,1944.0,1944.0,...,0.0,0.0,High PA -- Met score >= 3000,Yes,01 0017,India,4.LIC,1.0,1.0,1.002010e+09
17,1.001002e+07,10200121.0,0.0,0.0,0.0,0.0,0.0,0.0,2055.0,2055.0,...,0.0,0.0,Moderate PA -- Met score in 600-3000,Yes,01 0018,India,4.LIC,1.0,1.0,1.002010e+09
18,1.001002e+07,10200101.0,0.0,0.0,0.0,0.0,0.0,0.0,2109.0,2109.0,...,0.0,2880.0,High PA -- Met score >= 3000,Yes,01 0019,India,4.LIC,1.0,1.0,1.003010e+09
19,1.001002e+07,10200131.0,0.0,0.0,0.0,0.0,0.0,0.0,2056.0,2056.0,...,1335.0,0.0,High PA -- Met score >= 3000,Yes,01 0020,India,4.LIC,1.0,1.0,1.001010e+09
20,1.001002e+07,10200111.0,0.0,0.0,0.0,0.0,0.0,0.0,2056.0,2056.0,...,42.0,0.0,Moderate PA -- Met score in 600-3000,Yes,01 0021,India,4.LIC,1.0,1.0,1.003010e+09
21,1.001002e+07,10200122.0,0.0,0.0,0.0,0.0,0.0,0.0,2055.0,2055.0,...,3150.0,0.0,High PA -- Met score >= 3000,Yes,01 0022,India,4.LIC,1.0,1.0,1.002010e+09
22,1.001002e+07,10200132.0,0.0,0.0,0.0,0.0,0.0,0.0,2056.0,2056.0,...,420.0,0.0,Low PA -- Met score < 600,No,01 0023,India,4.LIC,1.0,1.0,1.001010e+09
23,1.001002e+07,10200142.0,0.0,0.0,0.0,0.0,0.0,0.0,4828.0,4828.0,...,787.5,0.0,High PA -- Met score >= 3000,Yes,01 0024,India,4.LIC,1.0,1.0,1.001010e+09
24,1.001002e+07,10200151.0,0.0,0.0,0.0,0.0,0.0,0.0,5200.0,5200.0,...,448.0,3360.0,High PA -- Met score >= 3000,Yes,01 0025,India,4.LIC,1.0,1.0,1.001010e+09
25,1.001003e+07,10200152.0,0.0,0.0,0.0,0.0,0.0,0.0,738.0,738.0,...,630.0,0.0,Moderate PA -- Met score in 600-3000,Yes,01 0026,India,4.LIC,1.0,1.0,1.001010e+09
26,1.001003e+07,10200165.0,0.0,1.0,0.0,0.0,1.0,1.0,2791.0,2946.0,...,525.0,0.0,Low PA -- Met score < 600,No,01 0027,India,4.LIC,1.0,1.0,1.005010e+09
27,1.001003e+07,10200171.0,0.0,0.0,0.0,0.0,0.0,0.0,6035.0,6035.0,...,0.0,0.0,Low PA -- Met score < 600,No,01 0028,India,4.LIC,1.0,1.0,1.004010e+09
28,1.001003e+07,10200161.0,0.0,0.0,0.0,0.0,0.0,0.0,6004.0,6004.0,...,0.0,1440.0,High PA -- Met score >= 3000,Yes,01 0029,India,4.LIC,1.0,1.0,1.005010e+09
29,1.001003e+07,10200181.0,0.0,0.0,0.0,0.0,0.0,0.0,2052.0,2052.0,...,1260.0,1440.0,High PA -- Met score >= 3000,Yes,01 0030,India,4.LIC,1.0,1.0,1.002010e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145712,6.200302e+10,65032381.0,0.0,0.0,0.0,0.0,0.0,0.0,4452.0,4452.0,...,630.0,0.0,Moderate PA -- Met score in 600-3000,Yes,,India,4.LIC,6.0,3.0,6.200302e+08
145713,6.200302e+10,65032382.0,0.0,0.0,0.0,0.0,0.0,0.0,1612.0,1612.0,...,0.0,0.0,Low PA -- Met score < 600,No,,India,4.LIC,6.0,3.0,6.200302e+08
145714,6.200302e+10,65032391.0,0.0,0.0,0.0,0.0,0.0,0.0,4335.0,4335.0,...,5040.0,0.0,High PA -- Met score >= 3000,Yes,,India,4.LIC,6.0,3.0,6.200302e+08
145715,6.200302e+10,65032392.0,0.0,0.0,0.0,0.0,0.0,0.0,4446.0,4446.0,...,0.0,0.0,Low PA -- Met score < 600,No,,India,4.LIC,6.0,3.0,6.200302e+08
145716,6.200302e+10,65032394.0,0.0,0.0,0.0,0.0,0.0,0.0,4726.0,4726.0,...,2940.0,0.0,Moderate PA -- Met score in 600-3000,Yes,,India,4.LIC,6.0,3.0,6.200302e+08
145717,6.200302e+10,65032402.0,0.0,0.0,0.0,0.0,0.0,0.0,4475.0,4475.0,...,1260.0,0.0,Moderate PA -- Met score in 600-3000,Yes,,India,4.LIC,6.0,3.0,6.200302e+08
145718,6.200302e+10,65032412.0,0.0,1.0,0.0,0.0,1.0,1.0,4263.0,4446.0,...,630.0,0.0,Moderate PA -- Met score in 600-3000,Yes,,India,4.LIC,6.0,3.0,6.200302e+08
145719,6.200302e+10,65032421.0,0.0,0.0,0.0,0.0,0.0,0.0,4475.0,4475.0,...,0.0,0.0,Low PA -- Met score < 600,No,,India,4.LIC,6.0,3.0,6.200302e+08
145720,6.200302e+10,65032432.0,0.0,0.0,0.0,0.0,0.0,0.0,4456.0,4456.0,...,1260.0,0.0,Moderate PA -- Met score in 600-3000,Yes,,India,4.LIC,6.0,3.0,6.200302e+08
145721,6.200302e+10,65032442.0,1.0,0.0,0.0,0.0,0.0,0.0,4459.0,4459.0,...,1260.0,0.0,Moderate PA -- Met score in 600-3000,Yes,,India,4.LIC,6.0,3.0,6.200302e+08
145722,6.200302e+10,65032451.0,0.0,0.0,0.0,0.0,0.0,0.0,4442.0,4442.0,...,0.0,0.0,Low PA -- Met score < 600,No,,India,4.LIC,6.0,3.0,6.200302e+08
145723,6.200302e+10,65032452.0,0.0,0.0,0.0,0.0,0.0,0.0,4428.0,4428.0,...,1260.0,0.0,Moderate PA -- Met score in 600-3000,Yes,,India,4.LIC,6.0,3.0,6.200302e+08
145724,6.200302e+10,65032456.0,0.0,0.0,0.0,0.0,0.0,0.0,4428.0,4428.0,...,0.0,0.0,Low PA -- Met score < 600,No,,India,4.LIC,6.0,3.0,6.200302e+08
145725,6.200302e+10,65032459.0,0.0,0.0,0.0,0.0,0.0,0.0,4401.0,4401.0,...,1260.0,0.0,Moderate PA -- Met score in 600-3000,Yes,,India,4.LIC,6.0,3.0,6.200302e+08
145726,6.200302e+10,65032462.0,0.0,1.0,0.0,0.0,1.0,1.0,3693.0,4455.0,...,0.0,0.0,Low PA -- Met score < 600,No,,India,4.LIC,6.0,3.0,6.200302e+08
145727,6.200302e+10,65032471.0,0.0,0.0,0.0,0.0,0.0,0.0,4461.0,4461.0,...,1680.0,0.0,High PA -- Met score >= 3000,Yes,,India,4.LIC,6.0,3.0,6.200302e+08
145728,6.200302e+10,65032472.0,0.0,0.0,0.0,0.0,0.0,0.0,4462.0,4462.0,...,112.5,0.0,Low PA -- Met score < 600,No,,India,4.LIC,6.0,3.0,6.200302e+08
145729,6.200302e+10,65032481.0,0.0,0.0,0.0,0.0,0.0,0.0,4456.0,4456.0,...,1680.0,0.0,Moderate PA -- Met score in 600-3000,Yes,,India,4.LIC,6.0,3.0,6.200302e+08
145730,6.200302e+10,65032492.0,0.0,0.0,0.0,0.0,0.0,0.0,4455.0,4455.0,...,0.0,0.0,Low PA -- Met score < 600,No,,India,4.LIC,6.0,3.0,6.200302e+08
145731,6.200303e+10,65032501.0,0.0,0.0,0.0,0.0,0.0,0.0,4475.0,4475.0,...,0.0,0.0,High PA -- Met score >= 3000,Yes,,India,4.LIC,6.0,3.0,6.200302e+08
145732,6.200303e+10,65032512.0,0.0,0.0,0.0,0.0,0.0,0.0,4448.0,4448.0,...,4620.0,0.0,High PA -- Met score >= 3000,Yes,,India,4.LIC,6.0,3.0,6.200303e+08
145733,6.200303e+10,65032522.0,0.0,0.0,1.0,0.0,1.0,1.0,18.0,18.0,...,2970.0,0.0,Moderate PA -- Met score in 600-3000,Yes,,India,4.LIC,6.0,3.0,6.200303e+08
145734,6.200303e+10,65032521.0,0.0,0.0,0.0,0.0,0.0,0.0,4454.0,4454.0,...,0.0,0.0,Low PA -- Met score < 600,No,,India,4.LIC,6.0,3.0,6.200303e+08
145735,6.200303e+10,65032531.0,0.0,0.0,0.0,0.0,0.0,0.0,4692.0,4692.0,...,3360.0,0.0,High PA -- Met score >= 3000,Yes,,India,4.LIC,6.0,3.0,6.200303e+08
145736,6.200303e+10,65032532.0,0.0,0.0,0.0,0.0,0.0,0.0,4691.0,4691.0,...,1260.0,0.0,Moderate PA -- Met score in 600-3000,Yes,,India,4.LIC,6.0,3.0,6.200303e+08
145737,6.200303e+10,65032542.0,0.0,0.0,0.0,0.0,0.0,0.0,4428.0,4428.0,...,5715.0,0.0,High PA -- Met score >= 3000,Yes,,India,4.LIC,6.0,3.0,6.200303e+08
145738,6.200303e+10,65032551.0,0.0,0.0,0.0,0.0,0.0,0.0,4431.0,4431.0,...,3360.0,6720.0,High PA -- Met score >= 3000,Yes,,India,4.LIC,6.0,3.0,6.200303e+08
145739,6.200303e+10,65032562.0,0.0,0.0,0.0,0.0,0.0,0.0,4434.0,4434.0,...,1260.0,0.0,Moderate PA -- Met score in 600-3000,Yes,,India,4.LIC,6.0,3.0,6.200303e+08
145740,6.200303e+10,65032571.0,0.0,0.0,0.0,0.0,0.0,0.0,4424.0,4424.0,...,0.0,0.0,Moderate PA -- Met score in 600-3000,Yes,,India,4.LIC,6.0,3.0,6.200303e+08
145741,6.200303e+10,65032578.0,0.0,0.0,0.0,0.0,0.0,0.0,3507.0,3507.0,...,0.0,0.0,Low PA -- Met score < 600,No,,India,4.LIC,6.0,3.0,6.200303e+08

In [130]:
non_null_merged_data = non_null_merged_data.dropna()

In [131]:
non_null_merged_data.count()

idno             123439
aid              123439
newdiab          123439
newmi            123439
newstrk          123439
newhf            123439
cvd              123439
severecvd        123439
fday_mi          123439
fday_strk        123439
fday_hf          123439
fday_cvd         123439
fday_sevcvd      123439
fday_dm          123439
fup              123439
dairy            123439
fruits           123439
vegets           123439
meats            123439
redmeat          123439
wtmeat           123439
fish             123439
starch           123439
sfdrink          123439
procfood         123439
transfat         123439
dairy_g          123439
fruits_g         123439
vegets_g         123439
meats_g          123439
                  ...
vigworkmet       123439
metjob           123439
vighousmet       123439
modhousoutmet    123439
modhousinmet     123439
methouse         123439
walkrecmet       123439
vigrecmet        123439
modrecmet        123439
metrecrt         123439
metall           123439
job_all          123439
trans_all        123439
house_all        123439
recrt_all        123439
metsit           123439
totsitall        123439
avgsitall        123439
metrecrt525      123439
totwalkmet       123439
totmodmet        123439
totvigmet        123439
physact          123439
metguide         123439
studyid          123439
key_country_y    123439
key_incctry_y    123439
key_centid_y     123439
key_commid_y     123439
key_hhid_y       123439
Length: 182, dtype: int64

In [132]:
X_all = non_null_merged_data.drop(columns=["idno", "newdiab"])
y_all = non_null_merged_data["newdiab"] # we should be able to index back in (assuming we kept the index)

In [133]:
for col in sorted(X_all.columns):
    print(col)

aheiscore
aid
applicationversion
avgsitall
cadary
calcium
carbohydrt
centid_x
centid_y
cescas_id
cholestrl
country
countryname
createddate
ctry
ctryp_x
ctryp_y
cvd
dairy
dairy_g
dairy_s
energ_kcal
epochid_x
epochid_y
fa_mono
fa_poly
fa_sat
fday_cvd
fday_dm
fday_hf
fday_mi
fday_sevcvd
fday_strk
fiber_td
fibs
fish
fish_g
fish_s
folate_tot
fruitcat
fruits
fruits_g
fruits_s
fruitsc
frvg
frys
fup
gdpctry
gdpctryr
house_all
incctry
incctryn
incctrynn
iron
job_all
key_centid_x
key_centid_y
key_commid_x
key_commid_y
key_country_x
key_country_y
key_hhid_x
key_hhid_y
key_incctry_x
key_incctry_y
lastmodifiedby
lastmodifieddate
legumes
legumes_g
legumes_s
leisactv1
leisactv2
leisactv3
leisphysact
lipid_tot
localcode
location
meats
meats_g
meats_s
metall
metguide
methouse
metjob
metrecrt
metrecrt525
metsit
modhousinmet
modhousoutmet
modrecmet
new_centid
new_country
newhf
newmi
newstrk
nutsc
paq_internalguid
paqfi
paqln
pchminswk
pcjob
percho
permufa
perprotein
perpufa
persatfat
pertotfat
peru_id
phase
phmminswk
phmpminswk
phvminswk
physact
pintcode
poccup
potassium
procfood
procfood_g
procfood_s
protdary
protein
prsmminswk
prsvminswk
prswminswk
psfat
psfats
recrt_all
redmeat
redmeat_g
redmeat_s
region
region2
region2a
regionn
ribolfavin
saltfood_g
severecvd
sfdrink
sfdrink_g
sfdrink_s
sodium
starch
starch_g
starch_s
studyid
subinpaq
subjectkey
sweets_g
thiamin
totmodmet
totsitall
totvigmet
totwalkmet
trans_all
transfat
transfat_g
transfat_s
vegetcat
vegets
vegets_g
vegets_s
vegs
version
vighousmet
vigrecmet
vigworkmet
vit_b6
vit_c
vit_e
walkrecmet
whitemeat
whitemeat_g
whitemeat_s
wojfruit_g
wtmeat
wtmeat_g
wtmeat_s
wtredr
wtredrs
zinc

In [134]:
# some of these columns have 
len(X_all.columns)

180

In [135]:
# check the data type of the columns
print(X_all["ctryp"])

KeyError: 'ctryp'

In [136]:
for col in sorted(X_all.columns):
    print(col, X_all[col].dtype)
    
#     we could drop all the cateogires. If we have category, then we can also do a look up. That is, 
# we can try some sort of conversion from category to one hot categorical vector. But we need some sort of 
# transformer that does that! 
# ALSO, recall the data science spark datacamp tutorial! 
# that one was roughly pretty good
# Recall, we had info on how we can do various transformation methods, such as string binarization etc.

'''
The overall pipeline is as follows: 
1. We will have some EDA

df = pd.read_csv() etc.

2. We will then massage the data into the format necessary for the sklearn algo: 
3. model should be built, and then accepts the dataframe

'''

aheiscore float64
aid float64
applicationversion object
avgsitall float64
cadary float64
calcium float64
carbohydrt float64
centid_x category
centid_y category
cescas_id object
cholestrl float64
country category
countryname object
createddate object
ctry category
ctryp_x category
ctryp_y category
cvd float64
dairy float64
dairy_g float64
dairy_s float64
energ_kcal float64
epochid_x float64
epochid_y float64
fa_mono float64
fa_poly float64
fa_sat float64
fday_cvd float64
fday_dm float64
fday_hf float64
fday_mi float64
fday_sevcvd float64
fday_strk float64
fiber_td float64
fibs float64
fish float64
fish_g float64
fish_s float64
folate_tot float64
fruitcat float64
fruits float64
fruits_g float64
fruits_s float64
fruitsc float64
frvg category
frys float64
fup float64
gdpctry category
gdpctryr float64
house_all float64
incctry category
incctryn float64
incctrynn float64
iron float64
job_all float64
key_centid_x float64
key_centid_y float64
key_commid_x float64
key_commid_y float64
key_country_x category
key_country_y category
key_hhid_x float64
key_hhid_y float64
key_incctry_x category
key_incctry_y category
lastmodifiedby object
lastmodifieddate object
legumes float64
legumes_g float64
legumes_s float64
leisactv1 category
leisactv2 category
leisactv3 category
leisphysact float64
lipid_tot float64
localcode object
location float64
meats float64
meats_g float64
meats_s float64
metall float64
metguide category
methouse float64
metjob float64
metrecrt float64
metrecrt525 float64
metsit float64
modhousinmet float64
modhousoutmet float64
modrecmet float64
new_centid float64
new_country float64
newhf float64
newmi float64
newstrk float64
nutsc float64
paq_internalguid object
paqfi object
paqln object
pchminswk float64
pcjob float64
percho float64
permufa float64
perprotein float64
perpufa float64
persatfat float64
pertotfat float64
peru_id object
phase category
phmminswk float64
phmpminswk float64
phvminswk float64
physact category
pintcode object
poccup object
potassium float64
procfood float64
procfood_g float64
procfood_s float64
protdary float64
protein float64
prsmminswk float64
prsvminswk float64
prswminswk float64
psfat float64
psfats float64
recrt_all float64
redmeat float64
redmeat_g float64
redmeat_s float64
region category
region2 category
region2a category
regionn category
ribolfavin float64
saltfood_g float64
severecvd float64
sfdrink float64
sfdrink_g float64
sfdrink_s float64
sodium float64
starch float64
starch_g float64
starch_s float64
studyid object
subinpaq object
subjectkey object
sweets_g float64
thiamin float64
totmodmet float64
totsitall float64
totvigmet float64
totwalkmet float64
trans_all float64
transfat float64
transfat_g float64
transfat_s float64
vegetcat float64
vegets float64
vegets_g float64
vegets_s float64
vegs float64
version object
vighousmet float64
vigrecmet float64
vigworkmet float64
vit_b6 float64
vit_c float64
vit_e float64
walkrecmet float64
whitemeat float64
whitemeat_g float64
whitemeat_s float64
wojfruit_g float64
wtmeat float64
wtmeat_g float64
wtmeat_s float64
wtredr float64
wtredrs float64
zinc float64

'\nThe overall pipeline is as follows: \n1. We will have some EDA\n\ndf = pd.read_csv() etc.\n\n2. We will then massage the data into the format necessary for the sklearn algo: \n3. model should be built, and then accepts the dataframe\n\n'

In [137]:
X_all.head()

,aid,newmi,newstrk,newhf,cvd,severecvd,fday_mi,fday_strk,fday_hf,fday_cvd,...,totmodmet,totvigmet,physact,metguide,studyid,key_country_y,key_incctry_y,key_centid_y,key_commid_y,key_hhid_y
0,10201921.0,0.0,0.0,0.0,0.0,0.0,2078.0,2078.0,2078.0,2078.0,...,0.0,0.0,Low PA -- Met score < 600,No,01 0001,India,4.LIC,1.0,1.0,1.002010e+09
1,10220021.0,0.0,0.0,0.0,0.0,0.0,1937.0,1937.0,1937.0,1937.0,...,540.0,0.0,High PA -- Met score >= 3000,Yes,01 0002,India,4.LIC,1.0,1.0,1.003010e+09
2,10210011.0,0.0,0.0,0.0,0.0,0.0,2699.0,2699.0,2699.0,2699.0,...,0.0,0.0,Moderate PA -- Met score in 600-3000,Yes,01 0003,India,4.LIC,1.0,1.0,1.005010e+09
3,10200091.0,0.0,0.0,0.0,0.0,0.0,6027.0,6027.0,6027.0,6027.0,...,630.0,0.0,Moderate PA -- Met score in 600-3000,Yes,01 0004,India,4.LIC,1.0,1.0,1.001010e+09
4,10210021.0,0.0,0.0,0.0,1.0,0.0,2706.0,2706.0,2706.0,2260.0,...,0.0,0.0,High PA -- Met score >= 3000,Yes,01 0005,India,4.LIC,1.0,1.0,1.004010e+09

In [138]:
# drop all the columns with category. 
# X_all.categorical
# to_be_dropped=pd.DataFrame(X_all.categorical).columns
X_all= X_all.select_dtypes(['number'])

In [139]:
X_all.count()

aid              123439
newmi            123439
newstrk          123439
newhf            123439
cvd              123439
severecvd        123439
fday_mi          123439
fday_strk        123439
fday_hf          123439
fday_cvd         123439
fday_sevcvd      123439
fday_dm          123439
fup              123439
dairy            123439
fruits           123439
vegets           123439
meats            123439
redmeat          123439
wtmeat           123439
fish             123439
starch           123439
sfdrink          123439
procfood         123439
transfat         123439
dairy_g          123439
fruits_g         123439
vegets_g         123439
meats_g          123439
redmeat_g        123439
wtmeat_g         123439
                  ...
phmminswk        123439
phmpminswk       123439
prswminswk       123439
prsvminswk       123439
prsmminswk       123439
vigworkmet       123439
metjob           123439
vighousmet       123439
modhousoutmet    123439
modhousinmet     123439
methouse         123439
walkrecmet       123439
vigrecmet        123439
modrecmet        123439
metrecrt         123439
metall           123439
job_all          123439
trans_all        123439
house_all        123439
recrt_all        123439
metsit           123439
totsitall        123439
avgsitall        123439
metrecrt525      123439
totwalkmet       123439
totmodmet        123439
totvigmet        123439
key_centid_y     123439
key_commid_y     123439
key_hhid_y       123439
Length: 140, dtype: int64

In [140]:
# Now, we import the sci-kit learn and do everything for prediction
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2)

In [141]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# scaler.fit(X_train)
# X_train = scaler.transform(X_train)
# X_test = scaler.transform(X_test)

# # a couple things: we want to

In [142]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=2)
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=2, p=2,
           weights='uniform')

In [143]:
knn_y_pred = knn_classifier.predict(X_test)

In [144]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
print(confusion_matrix(y_test, knn_y_pred))
print(classification_report(y_test, knn_y_pred))
print(roc_auc_score(y_test, knn_y_pred))

[[23713    18]
 [  892    65]]
             precision    recall  f1-score   support

        0.0       0.96      1.00      0.98     23731
        1.0       0.78      0.07      0.13       957

avg / total       0.96      0.96      0.95     24688

0.533581041812

In [145]:

from sklearn.ensemble import RandomForestClassifier
rfclassifier = RandomForestClassifier()
rfclassifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [146]:

rf_y_pred = rfclassifier.predict(X_test)

In [147]:
print(confusion_matrix(y_test, rf_y_pred))
print(classification_report(y_test, rf_y_pred))
print(roc_auc_score(y_test, rf_y_pred))

[[23728     3]
 [  422   535]]
             precision    recall  f1-score   support

        0.0       0.98      1.00      0.99     23731
        1.0       0.99      0.56      0.72       957

avg / total       0.98      0.98      0.98     24688

0.779456122782

In [35]:
Combpaq.describe()

NameError: name 'Combpaq' is not defined

In [ ]:
PBline.describe()

In [ ]:
PEvent.describe()

In [ ]:
PEvent.head()

In [ ]:
PFollow.describe()

In [ ]:
nutrition_vars = pd.read_table('nutritionVariables.txt', sep=',')

In [ ]:
cols = ['idno'] + list(nutrition_vars.abbreviation)
DF = Combffq[cols].merge(PEvent[['idno', 'newdiab']], left_on='idno', right_on='idno', how='inner')

In [ ]:
DF.describe()