In [1]:
import pandas as pd
import os

# A good example for data science pipeline
# https://courses.cs.ut.ee/MTAT.03.227/2019_fall/uploads/Main/python_tutorial

In [2]:
PATH = "/dhi_work/students/chenj4"

In [4]:
!ls "/dhi_work/students/chenj4"

Baseline_allcountry_ahei_AllVars_2019-01-16.xlsx
Baseline_allcountry_ahei_AllVars_2019-01-16.xlsx.csv
Baseline_combpaq_AllVars_2019-01-16.xlsx
Baseline_combpaq_AllVars_2019-01-16.xlsx.csv
Baseline_morevarspureadult_AllVars_2019-01-16.xlsx
Baseline_morevarspureadult_AllVars_2019-01-16.xlsx.csv
PURE_diabetes

In [5]:
!ls -al "/dhi_work/students/chenj4"

total 400
drwx------ 3 chenj4  studies   4096 Mar 20 17:27 .
drwxr-xr-x 4 nelsonw studies   4096 Mar  9 20:32 ..
-rw-r--r-- 1 chenj4  studies  16847 Mar 20 17:27 Baseline_allcountry_ahei_AllVars_2019-01-16.xlsx
-rw-r--r-- 1 chenj4  studies  11766 Mar 20 17:25 Baseline_allcountry_ahei_AllVars_2019-01-16.xlsx.csv
-rw-r--r-- 1 chenj4  studies  22816 Mar 20 17:27 Baseline_combpaq_AllVars_2019-01-16.xlsx
-rw-r--r-- 1 chenj4  studies  21485 Mar 20 17:25 Baseline_combpaq_AllVars_2019-01-16.xlsx.csv
-rw-r--r-- 1 chenj4  studies 130622 Mar 20 17:27 Baseline_morevarspureadult_AllVars_2019-01-16.xlsx
-rw-r--r-- 1 chenj4  studies 166112 Mar 20 17:25 Baseline_morevarspureadult_AllVars_2019-01-16.xlsx.csv
drwx------ 2 chenj4  studies   4096 Mar  9 20:26 PURE_diabetes

In [6]:
!ls -al "/dhi_work/students/chenj4/PURE_diabetes"

total 1052208
drwx------ 2 chenj4 studies      4096 Mar  9 20:26 .
drwx------ 3 chenj4 studies      4096 Mar 20 17:27 ..
-rwx------ 1 chenj4 studies 211030727 Mar  9 20:26 Combffq_04Apr19.dta
-rwx------ 1 chenj4 studies 397679602 Mar  9 20:26 Combpaq_04Apr19.dta
-rwx------ 1 chenj4 studies     24763 Mar  9 20:26 PAQ_Derived_2018-05-31.xlsx
-rwx------ 1 chenj4 studies 223129693 Mar  9 20:26 PBline_04Apr19.dta
-rwx------ 1 chenj4 studies  20926356 Mar  9 20:26 PEvent_04Apr19.dta
-rwx------ 1 chenj4 studies 220367908 Mar  9 20:26 PFollow_04Apr19.dta
-rwx------ 1 chenj4 studies     24612 Mar  9 20:26 ahei_derived_2018-05-31.xlsx

In [7]:
PATH = "/dhi_work/students/chenj4/PURE_diabetes"

In [8]:
Combffq = pd.read_stata(os.path.join(PATH, 'Combffq_04Apr19.dta'))
# Combpaq = pd.read_stata(os.path.join(PATH, 'Combpaq_04Apr19.dta'))
# PBline = pd.read_stata(os.path.join(PATH, 'PBline_04Apr19.dta'))
PEvent = pd.read_stata(os.path.join(PATH, 'PEvent_04Apr19.dta'))
# PFollow = pd.read_stata(os.path.join(PATH, 'PFollow_04Apr19.dta'))

In [9]:
Combffq.count()

idno           155147
dairy          151439
fruits         151438
vegets         151439
meats          151439
redmeat        151439
wtmeat         151439
fish           151439
starch         151439
sfdrink        149502
alcohol        119611
saltfood       147735
procfood       149781
transfat       151439
nuts           138540
dairy_g        155147
fruits_g       155146
vegets_g       155147
meats_g        155147
redmeat_g      155147
wtmeat_g       155147
fish_g         155147
starch_g       155147
sfdrink_g      153210
alcohol_g      123319
saltfood_g     151443
procfood_g     153489
transfat_g     155147
nuts_g         142248
fibcereal      146714
                ...
lycopene       101890
lutzea         101890
vit_e          150418
vit_k          103761
fa_sat         155147
fa_mono        155147
fa_poly        155147
cholestrl      152200
wtredr         155147
psfat          155147
pertotfat      155147
persatfat      155147
perprotein     155147
percho         155147
permufa        155147
perpufa        155147
vegs           155147
fruitsc        155147
nutsc          155147
wtredrs        155147
fibs           155147
psfats         155147
frys           155147
aheiscore      155147
epochid        155147
key_country    155147
key_incctry    155147
key_centid     155147
key_commid     155147
key_hhid       155147
Length: 170, dtype: int64

In [10]:
# Combffq["idno"].intersect(PEvent["idno"])

In [11]:
PEvent.count()

idno           163466
subjid           3795
aid            163466
newdiab        163466
newmi          163466
newstrk        163466
newhf          163466
cvd            163466
severecvd      163466
fday_mi        161820
fday_strk      161820
fday_hf        161820
fday_cvd       161313
fday_sevcvd    161818
fday_dm        161821
fup            163466
dtype: int64

In [52]:
# let's try joining!
merged_data = PEvent.merge(Combffq,how="inner", on="idno")

In [53]:
merged_data.count()

idno           151685
subjid           3468
aid            151685
newdiab        151685
newmi          151685
newstrk        151685
newhf          151685
cvd            151685
severecvd      151685
fday_mi        150287
fday_strk      150287
fday_hf        150287
fday_cvd       149796
fday_sevcvd    150285
fday_dm        150288
fup            151685
dairy          148012
fruits         148011
vegets         148012
meats          148012
redmeat        148012
wtmeat         148012
fish           148012
starch         148012
sfdrink        146079
alcohol        119281
saltfood       144329
procfood       146375
transfat       148012
nuts           135753
                ...
lycopene       101107
lutzea         101107
vit_e          149414
vit_k          102969
fa_sat         151685
fa_mono        151685
fa_poly        151685
cholestrl      148742
wtredr         151685
psfat          151685
pertotfat      151685
persatfat      151685
perprotein     151685
percho         151685
permufa        151685
perpufa        151685
vegs           151685
fruitsc        151685
nutsc          151685
wtredrs        151685
fibs           151685
psfats         151685
frys           151685
aheiscore      151685
epochid        151685
key_country    151685
key_incctry    151685
key_centid     151685
key_commid     151685
key_hhid       151685
Length: 185, dtype: int64

In [64]:
merged_data.dropna().count()

idno           55
subjid         55
aid            55
newdiab        55
newmi          55
newstrk        55
newhf          55
cvd            55
severecvd      55
fday_mi        55
fday_strk      55
fday_hf        55
fday_cvd       55
fday_sevcvd    55
fday_dm        55
fup            55
dairy          55
fruits         55
vegets         55
meats          55
redmeat        55
wtmeat         55
fish           55
starch         55
sfdrink        55
alcohol        55
saltfood       55
procfood       55
transfat       55
nuts           55
               ..
lycopene       55
lutzea         55
vit_e          55
vit_k          55
fa_sat         55
fa_mono        55
fa_poly        55
cholestrl      55
wtredr         55
psfat          55
pertotfat      55
persatfat      55
perprotein     55
percho         55
permufa        55
perpufa        55
vegs           55
fruitsc        55
nutsc          55
wtredrs        55
fibs           55
psfats         55
frys           55
aheiscore      55
epochid        55
key_country    55
key_incctry    55
key_centid     55
key_commid     55
key_hhid       55
Length: 185, dtype: int64

In [65]:
merged_data.head()

,idno,subjid,aid,newdiab,newmi,newstrk,newhf,cvd,severecvd,fday_mi,...,fibs,psfats,frys,aheiscore,epochid,key_country,key_incctry,key_centid,key_commid,key_hhid
0,10010001.0,NaN,10201921.0,0.0,0.0,0.0,0.0,0.0,0.0,2078.0,...,1.548733,10.000000,10.000000,26.251899,1002.0,India,4.LIC,1.0,1.0,1.002010e+09
1,10010002.0,NaN,10220021.0,0.0,0.0,0.0,0.0,0.0,0.0,1937.0,...,3.736092,10.000000,10.000000,45.113296,1004.0,India,4.LIC,1.0,1.0,1.003010e+09
2,10010003.0,NaN,10210011.0,0.0,0.0,0.0,0.0,0.0,0.0,2699.0,...,0.890825,10.000000,10.000000,51.747791,1003.0,India,4.LIC,1.0,1.0,1.005010e+09
3,10010004.0,NaN,10200091.0,0.0,0.0,0.0,0.0,0.0,0.0,6027.0,...,1.346636,9.594277,9.655577,45.072267,1002.0,India,4.LIC,1.0,1.0,1.001010e+09
4,10010005.0,NaN,10210021.0,0.0,0.0,0.0,0.0,1.0,0.0,2706.0,...,2.399921,10.000000,0.000000,39.291816,1003.0,India,4.LIC,1.0,1.0,1.004010e+09

In [54]:
Combffq.describe()

,idno,dairy,fruits,vegets,meats,redmeat,wtmeat,fish,starch,sfdrink,...,nutsc,wtredrs,fibs,psfats,frys,aheiscore,epochid,key_centid,key_commid,key_hhid
count,1.551470e+05,151439.000000,151438.000000,151439.000000,151439.000000,151439.000000,151439.000000,151439.000000,151439.000000,149502.000000,...,155147.000000,155147.000000,155147.000000,155147.000000,155147.000000,155147.000000,155147.00000,155147.000000,155147.000000,1.551470e+05
mean,5.784417e+09,1.518995,2.606640,4.390162,3.137615,0.995289,0.806826,0.494211,6.998909,0.195372,...,3.239697,4.289085,4.113409,6.645522,7.917159,34.490049,39667.02789,39.422283,191.548164,2.194566e+08
std,9.161031e+09,1.882021,2.844350,3.400901,2.489689,1.165644,1.313002,1.134050,3.765946,0.617775,...,3.813702,3.962157,3.335867,2.540041,3.233065,8.358739,32562.47005,32.573157,235.150985,6.542335e+08
min,1.001000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,5.655246,1001.00000,1.000000,1.000000,2.005001e+06
25%,1.300207e+09,0.163934,0.786885,2.261124,1.547058,0.173940,0.159251,0.005479,4.357143,0.000000,...,0.000000,0.927719,1.402692,4.574277,7.048472,28.953150,12001.00000,12.000000,3.000000,1.455358e+07
50%,2.665715e+09,1.000000,1.812011,4.214286,2.562476,0.650313,0.464286,0.142857,6.315068,0.000000,...,1.428571,2.299049,2.932787,6.504496,10.000000,34.455418,23501.00000,23.000000,51.000000,5.700631e+07
75%,7.602833e+09,2.071429,3.438859,5.214286,4.050150,1.360656,0.937949,0.491803,9.000000,0.122120,...,5.911007,10.000000,6.612188,9.239586,10.000000,39.882417,72001.00000,72.000000,502.000000,8.600913e+07
max,6.201001e+10,50.000000,120.367681,132.000000,44.074643,20.571429,42.503214,41.717500,99.798858,12.065574,...,10.000000,10.000000,10.000000,10.000000,10.000000,70.000000,95512.00000,95.000000,999.000000,5.006010e+09

In [55]:
# for name in sorted(Combpaq.columns):
#     print (name)

In [56]:
PEvent[PEvent["newdiab"] == 1]["newdiab"].count()

6216

In [57]:
PEvent[PEvent["newdiab"] == 0]["newdiab"].count()

157250

In [58]:
PEvent[PEvent["newdiab"] == 1]["newdiab"].count()/PEvent["newdiab"].count()

0.038026256224535988

# Create the dataset for scikit-learn

In [61]:
merged_data.isna().sum().sort_values() # we should drop the subjid too! (unless we use it with something else)

idno                 0
fa_sat               0
ribolfavin           0
thiamin              0
vit_c                0
sodium               0
potassium            0
iron                 0
calcium              0
fiber_td             0
carbohydrt           0
lipid_tot            0
protein              0
energ_kcal           0
cadary               0
protdary             0
ctryp                0
centid               0
fa_mono              0
fa_poly              0
wtredr               0
psfat                0
key_centid           0
key_incctry          0
key_country          0
epochid              0
aheiscore            0
frys                 0
psfats               0
fibs                 0
                 ...
otherveg_g       47866
vegcooked_g      47866
vit_k            48716
glveg_s          49457
otherveg_s       49457
folate_dfe       50578
lycopene         50578
beta_crypt       50578
folic_acid       50578
lutzea           50578
food_folate      50578
vegcooked_s      51390
glveg            51539
otherveg         51539
vegcooked        51539
vegraw_g         54131
crucveg          54483
crucveg_g        54483
vegraw_s         55722
crucveg_s        56074
vegraw           57804
fruitjuice_g     58263
dyveg_g          59706
dyveg_s          59706
fruitjuice_s     59854
fruitjuice       61936
dyveg            63379
alpha_carot      84488
beta_carot       86157
subjid          148217
Length: 185, dtype: int64

In [63]:
148217/merged_data.count().sum()

0.0058689191439250683

In [51]:
merged_data = merged_data.dropna()

In [19]:
X_all = merged_data.drop(columns=["idno", "newdiab"])
y_all = merged_data["newdiab"] # we should be able to index back in (assuming we kept the index)

In [27]:
for col in sorted(X_all.columns):
    print(col)

aheiscore
aid
alcohol
alcohol_g
alcohol_s
alpha_carot
animalfat
animalprotein
ash
beta_carot
beta_crypt
cadary
calcium
carbohydrt
centid
cholestrl
copper
crucveg
crucveg_g
crucveg_s
ctryp
cvd
dairy
dairy_g
dairy_s
dairysfa
dyveg
dyveg_g
dyveg_s
energ_kcal
epochid
fa_mono
fa_poly
fa_sat
fday_cvd
fday_dm
fday_hf
fday_mi
fday_sevcvd
fday_strk
fibcereal
fiber_td
fibs
fish
fish_g
fish_s
fishonly
fishonly_g
fishonly_s
fishsfa
folate_dfe
folate_tot
folic_acid
food_folate
fruitcat
fruitjuice
fruitjuice_g
fruitjuice_s
fruits
fruits_g
fruits_s
fruitsc
frvg
frys
fup
glveg
glveg_g
glveg_s
iron
key_centid
key_commid
key_country
key_hhid
key_incctry
legumes
legumes_g
legumes_s
lipid_tot
lutzea
lycopene
magnesium
manganese
meatnoprocsfa
meats
meats_g
meats_s
meatsfa
newhf
newmi
newstrk
niacin
nutnosoy
nutnosoy_g
nutnosoy_s
nuts
nuts_g
nuts_s
nutsc
otherveg
otherveg_g
otherveg_s
panto_acid
percho
permufa
perprotein
perpufa
persatfat
pertotfat
phosphorus
potassium
procfood
procfood_g
procfood_s
procmeat
procmeat_g
procmeat_s
protdary
protein
psfat
psfats
redmeat
redmeat2
redmeat2_g
redmeat2_s
redmeat_g
redmeat_s
redmeatsfa
redprocsfa
retinol
ribolfavin
saltfood
saltfood_g
saltfood_s
selenium
severecvd
sfdrink
sfdrink_g
sfdrink_s
sodium
starch
starch_g
starch_s
subjid
sugar_tot
sweets
sweets_g
sweets_s
thiamin
transfat
transfat_g
transfat_s
vegcooked
vegcooked_g
vegcooked_s
vegetcat
vegets
vegets_g
vegets_s
vegraw
vegraw_g
vegraw_s
vegs
vit_a_iu
vit_a_rae
vit_b12
vit_b6
vit_c
vit_e
vit_k
water
whitemeat
whitemeat_g
whitemeat_s
whtmeatsfa
wojfruit
wojfruit_g
wojfruit_s
wtmeat
wtmeat_g
wtmeat_s
wtredr
wtredrs
zinc

In [26]:
# some of these columns have 
len(X_all.columns)

183

In [33]:
# check the data type of the columns
print(X_all["ctryp"])

0         India
1         India
2         India
3         India
4         India
5         India
6         India
7         India
8         India
9         India
10        India
11        India
12        India
13        India
14        India
15        India
16        India
17        India
18        India
19        India
20        India
21        India
22        India
23        India
24        India
25        India
26        India
27        India
28        India
29        India
          ...
151655    India
151656    India
151657    India
151658    India
151659    India
151660    India
151661    India
151662    India
151663    India
151664    India
151665    India
151666    India
151667    India
151668    India
151669    India
151670    India
151671    India
151672    India
151673    India
151674    India
151675    India
151676    India
151677    India
151678    India
151679    India
151680    India
151681    India
151682    India
151683    India
151684    India
Name: ctryp, Length: 151685, dtype: category
Categories (21, object): [Canada < Sweden < UAE < Saudi Arabia ... India < Pakistan < Zimbabwe < Tanzania]

In [37]:
for col in sorted(X_all.columns):
    print(col, X_all[col].dtype)
    
#     we could drop all the cateogires. If we have category, then we can also do a look up. That is, 
# we can try some sort of conversion from category to one hot categorical vector. But we need some sort of 
# transformer that does that! 
# ALSO, recall the data science spark datacamp tutorial! 
# that one was roughly pretty good
# Recall, we had info on how we can do various transformation methods, such as string binarization etc.

'''
The overall pipeline is as follows: 
1. We will have some EDA

df = pd.read_csv() etc.

2. We will then massage the data into the format necessary for the sklearn algo: 
3. model should be built, and then accepts the dataframe

'''

aheiscore float64
aid float64
alcohol float64
alcohol_g float64
alcohol_s float64
alpha_carot float64
animalfat float64
animalprotein float64
ash float64
beta_carot float64
beta_crypt float64
cadary float64
calcium float64
carbohydrt float64
centid category
cholestrl float64
copper float64
crucveg float64
crucveg_g float64
crucveg_s float64
ctryp category
cvd float64
dairy float64
dairy_g float64
dairy_s float64
dairysfa float64
dyveg float64
dyveg_g float64
dyveg_s float64
energ_kcal float64
epochid float64
fa_mono float64
fa_poly float64
fa_sat float64
fday_cvd float64
fday_dm float64
fday_hf float64
fday_mi float64
fday_sevcvd float64
fday_strk float64
fibcereal float64
fiber_td float64
fibs float64
fish float64
fish_g float64
fish_s float64
fishonly float64
fishonly_g float64
fishonly_s float64
fishsfa float64
folate_dfe float64
folate_tot float64
folic_acid float64
food_folate float64
fruitcat float64
fruitjuice float64
fruitjuice_g float64
fruitjuice_s float64
fruits float64
fruits_g float64
fruits_s float64
fruitsc float64
frvg category
frys float64
fup float64
glveg float64
glveg_g float64
glveg_s float64
iron float64
key_centid float64
key_commid float64
key_country category
key_hhid float64
key_incctry category
legumes float64
legumes_g float64
legumes_s float64
lipid_tot float64
lutzea float64
lycopene float64
magnesium float64
manganese float64
meatnoprocsfa float64
meats float64
meats_g float64
meats_s float64
meatsfa float64
newhf float64
newmi float64
newstrk float64
niacin float64
nutnosoy float64
nutnosoy_g float64
nutnosoy_s float64
nuts float64
nuts_g float64
nuts_s float64
nutsc float64
otherveg float64
otherveg_g float64
otherveg_s float64
panto_acid float64
percho float64
permufa float64
perprotein float64
perpufa float64
persatfat float64
pertotfat float64
phosphorus float64
potassium float64
procfood float64
procfood_g float64
procfood_s float64
procmeat float64
procmeat_g float64
procmeat_s float64
protdary float64
protein float64
psfat float64
psfats float64
redmeat float64
redmeat2 float64
redmeat2_g float64
redmeat2_s float64
redmeat_g float64
redmeat_s float64
redmeatsfa float64
redprocsfa float64
retinol float64
ribolfavin float64
saltfood float64
saltfood_g float64
saltfood_s float64
selenium float64
severecvd float64
sfdrink float64
sfdrink_g float64
sfdrink_s float64
sodium float64
starch float64
starch_g float64
starch_s float64
subjid float64
sugar_tot float64
sweets float64
sweets_g float64
sweets_s float64
thiamin float64
transfat float64
transfat_g float64
transfat_s float64
vegcooked float64
vegcooked_g float64
vegcooked_s float64
vegetcat float64
vegets float64
vegets_g float64
vegets_s float64
vegraw float64
vegraw_g float64
vegraw_s float64
vegs float64
vit_a_iu float64
vit_a_rae float64
vit_b12 float64
vit_b6 float64
vit_c float64
vit_e float64
vit_k float64
water float64
whitemeat float64
whitemeat_g float64
whitemeat_s float64
whtmeatsfa float64
wojfruit float64
wojfruit_g float64
wojfruit_s float64
wtmeat float64
wtmeat_g float64
wtmeat_s float64
wtredr float64
wtredrs float64
zinc float64

'\nThe overall pipeline is as follows: \n1. We will have some EDA\n\ndf = pd.read_csv() etc.\n\n2. We will then massage the data into the format necessary for the sklearn algo: \n3. model should be built, and then accepts the dataframe\n\n'

In [38]:
X_all.head()

,subjid,aid,newmi,newstrk,newhf,cvd,severecvd,fday_mi,fday_strk,fday_hf,...,fibs,psfats,frys,aheiscore,epochid,key_country,key_incctry,key_centid,key_commid,key_hhid
0,NaN,10201921.0,0.0,0.0,0.0,0.0,0.0,2078.0,2078.0,2078.0,...,1.548733,10.000000,10.000000,26.251899,1002.0,India,4.LIC,1.0,1.0,1.002010e+09
1,NaN,10220021.0,0.0,0.0,0.0,0.0,0.0,1937.0,1937.0,1937.0,...,3.736092,10.000000,10.000000,45.113296,1004.0,India,4.LIC,1.0,1.0,1.003010e+09
2,NaN,10210011.0,0.0,0.0,0.0,0.0,0.0,2699.0,2699.0,2699.0,...,0.890825,10.000000,10.000000,51.747791,1003.0,India,4.LIC,1.0,1.0,1.005010e+09
3,NaN,10200091.0,0.0,0.0,0.0,0.0,0.0,6027.0,6027.0,6027.0,...,1.346636,9.594277,9.655577,45.072267,1002.0,India,4.LIC,1.0,1.0,1.001010e+09
4,NaN,10210021.0,0.0,0.0,0.0,1.0,0.0,2706.0,2706.0,2706.0,...,2.399921,10.000000,0.000000,39.291816,1003.0,India,4.LIC,1.0,1.0,1.004010e+09

In [42]:
# drop all the columns with category. 
# X_all.categorical
# to_be_dropped=pd.DataFrame(X_all.categorical).columns
X_all= X_all.select_dtypes(['number'])

In [46]:
# drop the NAN columns too
X_all = X_all.dropna()

In [47]:
# Now, we import the sci-kit learn and do everything for prediction
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2)

ValueError: Found input variables with inconsistent numbers of samples: [55, 151685]

In [48]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# scaler.fit(X_train)
# X_train = scaler.transform(X_train)
# X_test = scaler.transform(X_test)

# # a couple things: we want to

In [49]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=2)
knn_classifier.fit(X_train, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
Combpaq.describe()

In [ ]:
PBline.describe()

In [ ]:
PEvent.describe()

In [23]:
PEvent.head()

,idno,subjid,aid,newdiab,newmi,newstrk,newhf,cvd,severecvd,fday_mi,fday_strk,fday_hf,fday_cvd,fday_sevcvd,fday_dm,fup
0,10010001.0,NaN,10201921.0,0.0,0.0,0.0,0.0,0.0,0.0,2078.0,2078.0,2078.0,2078.0,2078.0,2078.0,1.0
1,10010002.0,NaN,10220021.0,0.0,0.0,0.0,0.0,0.0,0.0,1937.0,1937.0,1937.0,1937.0,1937.0,1937.0,1.0
2,10010003.0,NaN,10210011.0,0.0,0.0,0.0,0.0,0.0,0.0,2699.0,2699.0,2699.0,2699.0,2699.0,2699.0,1.0
3,10010004.0,NaN,10200091.0,0.0,0.0,0.0,0.0,0.0,0.0,6027.0,6027.0,6027.0,6027.0,6027.0,6027.0,1.0
4,10010005.0,NaN,10210021.0,0.0,0.0,0.0,0.0,1.0,0.0,2706.0,2706.0,2706.0,2260.0,2706.0,2706.0,1.0

In [24]:
PFollow.describe()

NameError: name 'PFollow' is not defined

In [25]:
nutrition_vars = pd.read_table('nutritionVariables.txt', sep=',')

FileNotFoundError: File b'nutritionVariables.txt' does not exist

In [ ]:
cols = ['idno'] + list(nutrition_vars.abbreviation)
DF = Combffq[cols].merge(PEvent[['idno', 'newdiab']], left_on='idno', right_on='idno', how='inner')

In [ ]:
DF.describe()